<a href="https://colab.research.google.com/github/VitalyGladyshev/gb_rec_sys/blob/main/coursework/cw_rec_sys_glvv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ПРОЕКТ "Рекомендательные системы"

# ЧАСТЬ 2: Моделирование

In [8]:
# install implicit (it was installing by conda: conda install -c conda-forge implicit)

In [9]:
# install lightfm (it was installing by conda: conda install -c conda-forge lightfm)

In [137]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import random

# Для работы с матрицами
from scipy.sparse import csr_matrix

# Матричная факторизация
from implicit import als

# Модель второго уровня
from lightgbm import LGBMClassifier

import os, sys

In [2]:
path_to_src = './src'

In [126]:
if path_to_src not in sys.path:
    sys.path.append(path_to_src)

# Написанные функции
from metrics import precision_at_k, recall_at_k
from utils import prefilter_items
from recommenders import MainRecommender

In [7]:
path_to_files = './prep12'

In [34]:
data          = pd.read_csv(os.path.join(path_to_files, "data.csv"))
user_features = pd.read_csv(os.path.join(path_to_files, "user_features.csv"))
item_features = pd.read_csv(os.path.join(path_to_files, "item_features.csv"))

In [35]:
data

,user_id,basket_id,day,item_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc
0,2375,26984851472,1,999999,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,999999,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,999999,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,999999,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,999999,1,1.50,364,-0.39,1631,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2396799,1613,41655820646,663,999999,1,2.00,3262,-1.15,1231,95,0.0,0.0
2396800,1001,41655829421,663,999999,1,1.69,3131,0.00,2231,95,0.0,0.0
2396801,1001,41655829421,663,999999,1,1.69,3131,0.00,2231,95,0.0,0.0
2396802,1167,41656790510,663,999999,22451,43.98,3385,-0.65,1059,95,0.0,0.0
2396803,1167,41656790510,663,999999,1,8.00,3385,0.00,1059,95,0.0,0.0

In [11]:
user_features

,age_desc,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,user_id,bill_avg,week_last_bill,items_per_week
0,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1,2.492077,95,18.264368
1,45-54,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7,2.673405,95,11.780220
2,25-34,U,25-34K,Unknown,2 Adults Kids,3,1,8,2.798250,95,20.505882
3,25-34,U,75-99K,Homeowner,2 Adults Kids,4,2,13,5.693402,95,26.750000
4,45-54,B,50-74K,Homeowner,Single Female,1,None/Unknown,16,2.927602,94,6.412500
...,...,...,...,...,...,...,...,...,...,...,...
796,35-44,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2494,3.560885,93,6.230769
797,45-54,A,75-99K,Homeowner,Unknown,3,1,2496,2.891049,95,18.205128
798,45-54,U,35-49K,Unknown,Single Male,1,None/Unknown,2497,3.533885,95,23.349398
799,25-34,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2498,3.012473,95,10.544304
800,25-34,U,Under 15K,Unknown,2 Adults Kids,3,1,2499,2.966347,92,11.535714

In [12]:
item_features

,item_id,manufacturer,department,brand,commodity_desc,sub_commodity_desc,curr_size_of_product
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ
...,...,...,...,...,...,...,...
92348,18293142,6384,DRUG GM,National,BOOKSTORE,PAPERBACK BOOKS,
92349,18293439,6393,DRUG GM,National,BOOKSTORE,CHILDRENS LOW END,
92350,18293696,6406,DRUG GM,National,BOOKSTORE,PAPERBACK BEST SELLER,
92351,18294080,6442,DRUG GM,National,BOOKSTORE,PAPERBACK BOOKS,
92352,18316298,764,GROCERY,National,PAPER TOWELS,PAPER TOWELS & HOLDERS,

### Проверочные и тестовые мероприятия

In [13]:
user_item_matrix = pd.pivot_table(data, 
                                          index='user_id',
                                          columns='item_id', 
                                          values='quantity', # Можно пробовать другие варианты
                                          aggfunc='count', 
                                          fill_value=0)
user_item_matrix

item_id,201704,818981,818996,819063,819112,819115,819210,819255,819304,819308,...,17104444,17105058,17105257,17106039,17168855,17169131,17179856,17179873,17208470,17214946
user_id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2500,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
from implicit.nearest_neighbours import bm25_weight, tfidf_weight

#user_item_matrix_tfidf = tfidf_weight(user_item_matrix.T).T
user_item_matrix_tfidf = tfidf_weight(user_item_matrix)
user_item_matrix_tfidf

<2499x12744 sparse matrix of type '<class 'numpy.float64'>'
	with 606929 stored elements in COOrdinate format>

In [16]:
user_item_matrix_bm25 = bm25_weight(user_item_matrix.T).T
user_item_matrix_bm25

<2499x12744 sparse matrix of type '<class 'numpy.float64'>'
	with 606929 stored elements in COOrdinate format>

In [17]:
def prepare_dicts(user_item_matrix):
        """Подготавливает вспомогательные словари"""

        userids = user_item_matrix.index.values
        itemids = user_item_matrix.columns.values

        matrix_userids = np.arange(len(userids))
        matrix_itemids = np.arange(len(itemids))

        id_to_itemid = dict(zip(matrix_itemids, itemids))
        id_to_userid = dict(zip(matrix_userids, userids))

        itemid_to_id = dict(zip(itemids, matrix_itemids))
        userid_to_id = dict(zip(userids, matrix_userids))

        return id_to_itemid, id_to_userid, itemid_to_id, userid_to_id

In [18]:
id_to_itemid, id_to_userid, \
        itemid_to_id, userid_to_id = prepare_dicts(user_item_matrix)

In [19]:
id_to_itemid

{0: 201704,
 1: 818981,
 2: 818996,
 3: 819063,
 4: 819112,
 5: 819115,
 6: 819210,
 7: 819255,
 8: 819304,
 9: 819308,
 10: 819330,
 11: 819400,
 12: 819487,
 13: 819518,
 14: 819534,
 15: 819578,
 16: 819590,
 17: 819594,
 18: 819612,
 19: 819765,
 20: 819840,
 21: 819845,
 22: 819849,
 23: 819927,
 24: 819969,
 25: 819978,
 26: 820011,
 27: 820082,
 28: 820122,
 29: 820291,
 30: 820296,
 31: 820301,
 32: 820321,
 33: 820347,
 34: 820352,
 35: 820429,
 36: 820486,
 37: 820518,
 38: 820551,
 39: 820582,
 40: 820612,
 41: 820701,
 42: 820752,
 43: 820788,
 44: 820895,
 45: 820923,
 46: 820950,
 47: 821007,
 48: 821025,
 49: 821032,
 50: 821083,
 51: 821134,
 52: 821174,
 53: 821200,
 54: 821209,
 55: 821219,
 56: 821316,
 57: 821324,
 58: 821344,
 59: 821464,
 60: 821465,
 61: 821556,
 62: 821565,
 63: 821695,
 64: 821741,
 65: 821761,
 66: 821787,
 67: 821788,
 68: 821825,
 69: 821845,
 70: 821863,
 71: 821890,
 72: 821895,
 73: 821923,
 74: 821930,
 75: 821970,
 76: 821974,
 77: 821976,
 78: 822049,
 79: 822066,
 80: 822073,
 81: 822101,
 82: 822115,
 83: 822140,
 84: 822161,
 85: 822178,
 86: 822225,
 87: 822226,
 88: 822236,
 89: 822259,
 90: 822346,
 91: 822348,
 92: 822407,
 93: 822517,
 94: 822524,
 95: 822558,
 96: 822646,
 97: 822739,
 98: 822781,
 99: 822785,
 100: 822812,
 101: 822860,
 102: 822892,
 103: 822941,
 104: 822944,
 105: 822953,
 106: 822965,
 107: 822966,
 108: 822970,
 109: 822985,
 110: 823031,
 111: 823098,
 112: 823099,
 113: 823176,
 114: 823194,
 115: 823255,
 116: 823266,
 117: 823356,
 118: 823365,
 119: 823475,
 120: 823503,
 121: 823530,
 122: 823565,
 123: 823576,
 124: 823641,
 125: 823646,
 126: 823687,
 127: 823704,
 128: 823709,
 129: 823721,
 130: 823767,
 131: 823775,
 132: 823790,
 133: 823862,
 134: 823915,
 135: 823990,
 136: 824005,
 137: 824037,
 138: 824072,
 139: 824073,
 140: 824074,
 141: 824122,
 142: 824180,
 143: 824193,
 144: 824209,
 145: 824255,
 146: 824291,
 147: 824303,
 148: 824305,
 149: 824311,
 150: 824396,
 151: 824546,
 152: 824593,
 153: 824605,
 154: 824758,
 155: 824759,
 156: 824789,
 157: 824796,
 158: 824813,
 159: 824846,
 160: 824915,
 161: 824923,
 162: 824931,
 163: 824970,
 164: 824977,
 165: 825006,
 166: 825118,
 167: 825123,
 168: 825153,
 169: 825170,
 170: 825176,
 171: 825180,
 172: 825208,
 173: 825218,
 174: 825226,
 175: 825289,
 176: 825295,
 177: 825313,
 178: 825317,
 179: 825326,
 180: 825343,
 181: 825365,
 182: 825412,
 183: 825494,
 184: 825538,
 185: 825541,
 186: 825550,
 187: 825556,
 188: 825616,
 189: 825621,
 190: 825625,
 191: 825659,
 192: 825665,
 193: 825670,
 194: 825703,
 195: 825731,
 196: 825748,
 197: 825749,
 198: 825751,
 199: 825850,
 200: 825882,
 201: 825970,
 202: 825976,
 203: 825994,
 204: 825999,
 205: 826004,
 206: 826067,
 207: 826090,
 208: 826099,
 209: 826120,
 210: 826144,
 211: 826239,
 212: 826265,
 213: 826272,
 214: 826385,
 215: 826419,
 216: 826566,
 217: 826571,
 218: 826580,
 219: 826597,
 220: 826666,
 221: 826695,
 222: 826784,
 223: 826816,
 224: 826830,
 225: 826835,
 226: 826842,
 227: 826860,
 228: 826900,
 229: 826952,
 230: 826984,
 231: 827024,
 232: 827047,
 233: 827050,
 234: 827079,
 235: 827133,
 236: 827175,
 237: 827180,
 238: 827261,
 239: 827271,
 240: 827332,
 241: 827361,
 242: 827373,
 243: 827393,
 244: 827394,
 245: 827546,
 246: 827570,
 247: 827578,
 248: 827631,
 249: 827656,
 250: 827667,
 251: 827671,
 252: 827683,
 253: 827749,
 254: 827781,
 255: 827802,
 256: 827806,
 257: 827911,
 258: 827919,
 259: 827999,
 260: 828048,
 261: 828055,
 262: 828073,
 263: 828106,
 264: 828114,
 265: 828143,
 266: 828219,
 267: 828278,
 268: 828283,
 269: 828328,
 270: 828331,
 271: 828370,
 272: 828385,
 273: 828393,
 274: 828412,
 275: 828437,
 276: 828490,
 277: 828516,
 278: 828557,
 279: 828588,
 280: 828713,
 281: 828732,
 282: 828867,
 283: 828901,
 284: 828935,
 285: 828993,
 286: 829001,
 287: 829116,
 288: 829138,
 289: 829266,
 290: 829278,
 291: 829291,
 292: 829323,
 293: 829349,
 294: 829427,
 295: 829456,
 296: 829491,
 297: 829495,
 298: 829515,
 299: 829550,
 300: 829563,
 301: 829617,
 302: 829621,
 303: 829645,
 304: 829662,
 305: 829685,
 306: 829722,
 307: 829802,
 308: 829823,
 309: 829852,
 310: 829866,
 311: 829920,
 312: 829928,
 313: 829950,
 314: 829955,
 315: 829958,
 316: 829972,
 317: 830015,
 318: 830070,
 319: 830097,
 320: 830125,
 321: 830156,
 322: 830202,
 323: 830203,
 324: 830245,
 325: 830304,
 326: 830374,
 327: 830503,
 328: 830526,
 329: 830582,
 330: 830615,
 331: 830677,
 332: 830686,
 333: 830701,
 334: 830775,
 335: 830783,
 336: 830790,
 337: 830795,
 338: 830850,
 339: 830887,
 340: 830935,
 341: 830941,
 342: 830965,
 343: 830973,
 344: 830976,
 345: 831063,
 346: 831091,
 347: 831124,
 348: 831125,
 349: 831161,
 350: 831181,
 351: 831223,
 352: 831246,
 353: 831296,
 354: 831331,
 355: 831371,
 356: 831390,
 357: 831407,
 358: 831509,
 359: 831545,
 360: 831557,
 361: 831559,
 362: 831587,
 363: 831628,
 364: 831712,
 365: 831728,
 366: 831763,
 367: 831888,
 368: 831937,
 369: 831965,
 370: 832001,
 371: 832007,
 372: 832207,
 373: 832221,
 374: 832249,
 375: 832270,
 376: 832285,
 377: 832288,
 378: 832335,
 379: 832373,
 380: 832394,
 381: 832442,
 382: 832473,
 383: 832492,
 384: 832513,
 385: 832526,
 386: 832544,
 387: 832678,
 388: 832746,
 389: 832760,
 390: 832768,
 391: 832785,
 392: 832828,
 393: 832937,
 394: 832976,
 395: 833014,
 396: 833025,
 397: 833151,
 398: 833155,
 399: 833169,
 400: 833193,
 401: 833238,
 402: 833241,
 403: 833273,
 404: 833347,
 405: 833351,
 406: 833383,
 407: 833436,
 408: 833458,
 409: 833494,
 410: 833577,
 411: 833583,
 412: 833591,
 413: 833598,
 414: 833648,
 415: 833724,
 416: 833754,
 417: 833841,
 418: 833849,
 419: 833866,
 420: 833870,
 421: 833940,
 422: 833969,
 423: 834009,
 424: 834086,
 425: 834102,
 426: 834117,
 427: 834129,
 428: 834158,
 429: 834303,
 430: 834382,
 431: 834391,
 432: 834396,
 433: 834399,
 434: 834435,
 435: 834465,
 436: 834491,
 437: 834516,
 438: 834565,
 439: 834572,
 440: 834631,
 441: 834662,
 442: 834715,
 443: 834777,
 444: 834826,
 445: 834833,
 446: 834842,
 447: 834846,
 448: 834911,
 449: 834915,
 450: 834932,
 451: 834952,
 452: 834962,
 453: 834993,
 454: 835004,
 455: 835017,
 456: 835028,
 457: 835058,
 458: 835077,
 459: 835080,
 460: 835098,
 461: 835236,
 462: 835243,
 463: 835247,
 464: 835278,
 465: 835279,
 466: 835285,
 467: 835296,
 468: 835300,
 469: 835347,
 470: 835394,
 471: 835431,
 472: 835476,
 473: 835482,
 474: 835499,
 475: 835530,
 476: 835558,
 477: 835578,
 478: 835595,
 479: 835604,
 480: 835616,
 481: 835618,
 482: 835619,
 483: 835675,
 484: 835715,
 485: 835783,
 486: 835796,
 487: 835819,
 488: 835943,
 489: 835973,
 490: 835977,
 491: 836043,
 492: 836085,
 493: 836090,
 494: 836163,
 495: 836258,
 496: 836286,
 497: 836423,
 498: 836445,
 499: 836645,
 500: 836703,
 501: 836745,
 502: 836758,
 503: 836891,
 504: 836916,
 505: 836924,
 506: 836952,
 507: 836964,
 508: 837005,
 509: 837012,
 510: 837073,
 511: 837107,
 512: 837139,
 513: 837167,
 514: 837242,
 515: 837270,
 516: 837304,
 517: 837339,
 518: 837366,
 519: 837413,
 520: 837495,
 521: 837527,
 522: 837561,
 523: 837569,
 524: 837579,
 525: 837602,
 526: 837644,
 527: 837647,
 528: 837664,
 529: 837669,
 530: 837677,
 531: 837684,
 532: 837720,
 533: 837751,
 534: 837864,
 535: 837865,
 536: 837908,
 537: 837969,
 538: 838010,
 539: 838050,
 540: 838097,
 541: 838136,
 542: 838186,
 543: 838210,
 544: 838261,
 545: 838319,
 546: 838347,
 547: 838369,
 548: 838396,
 549: 838554,
 550: 838563,
 551: 838571,
 552: 838602,
 553: 838637,
 554: 838712,
 555: 838733,
 556: 838738,
 557: 838739,
 558: 838797,
 559: 838829,
 560: 838842,
 561: 838859,
 562: 838867,
 563: 838882,
 564: 838971,
 565: 839035,
 566: 839094,
 567: 839112,
 568: 839152,
 569: 839162,
 570: 839188,
 571: 839191,
 572: 839192,
 573: 839208,
 574: 839225,
 575: 839243,
 576: 839248,
 577: 839262,
 578: 839346,
 579: 839419,
 580: 839438,
 581: 839485,
 582: 839605,
 583: 839653,
 584: 839656,
 585: 839747,
 586: 839766,
 587: 839818,
 588: 840173,
 589: 840227,
 590: 840244,
 591: 840255,
 592: 840322,
 593: 840386,
 594: 840566,
 595: 840601,
 596: 840609,
 597: 840640,
 598: 840732,
 599: 840735,
 600: 840764,
 601: 840890,
 602: 840938,
 603: 841016,
 604: 841025,
 605: 841035,
 606: 841159,
 607: 841220,
 608: 841223,
 609: 841228,
 610: 841236,
 611: 841266,
 612: 841287,
 613: 841309,
 614: 841327,
 615: 841443,
 616: 841469,
 617: 841478,
 618: 841584,
 619: 841606,
 620: 841683,
 621: 841686,
 622: 841762,
 623: 841872,
 624: 841899,
 625: 841905,
 626: 842068,
 627: 842091,
 628: 842125,
 629: 842140,
 630: 842170,
 631: 842249,
 632: 842264,
 633: 842286,
 634: 842350,
 635: 842368,
 636: 842385,
 637: 842392,
 638: 842407,
 639: 842416,
 640: 842423,
 641: 842434,
 642: 842455,
 643: 842470,
 644: 842474,
 645: 842522,
 646: 842530,
 647: 842558,
 648: 842647,
 649: 842698,
 650: 842704,
 651: 842707,
 652: 842762,
 653: 842769,
 654: 842783,
 655: 842795,
 656: 842886,
 657: 842930,
 658: 842995,
 659: 843013,
 660: 843111,
 661: 843114,
 662: 843116,
 663: 843127,
 664: 843171,
 665: 843206,
 666: 843239,
 667: 843259,
 668: 843306,
 669: 843338,
 670: 843339,
 671: 843346,
 672: 843361,
 673: 843376,
 674: 843418,
 675: 843441,
 676: 843450,
 677: 843464,
 678: 843558,
 679: 843567,
 680: 843656,
 681: 843689,
 682: 843728,
 683: 843744,
 684: 843756,
 685: 843819,
 686: 843891,
 687: 843898,
 688: 843911,
 689: 843929,
 690: 843951,
 691: 844054,
 692: 844155,
 693: 844165,
 694: 844166,
 695: 844169,
 696: 844175,
 697: 844179,
 698: 844278,
 699: 844282,
 700: 844413,
 701: 844424,
 702: 844441,
 703: 844462,
 704: 844493,
 705: 844498,
 706: 844652,
 707: 844697,
 708: 844740,
 709: 844748,
 710: 844759,
 711: 844818,
 712: 844839,
 713: 844929,
 714: 844991,
 715: 845052,
 716: 845053,
 717: 845078,
 718: 845082,
 719: 845091,
 720: 845109,
 721: 845163,
 722: 845193,
 723: 845196,
 724: 845208,
 725: 845265,
 726: 845294,
 727: 845307,
 728: 845319,
 729: 845348,
 730: 845370,
 731: 845379,
 732: 845432,
 733: 845462,
 734: 845622,
 735: 845675,
 736: 845677,
 737: 845705,
 738: 845715,
 739: 845774,
 740: 845868,
 741: 845894,
 742: 845896,
 743: 845914,
 744: 845975,
 745: 845992,
 746: 846014,
 747: 846015,
 748: 846032,
 749: 846043,
 750: 846045,
 751: 846114,
 752: 846202,
 753: 846270,
 754: 846285,
 755: 846301,
 756: 846334,
 757: 846380,
 758: 846417,
 759: 846429,
 760: 846466,
 761: 846482,
 762: 846502,
 763: 846550,
 764: 846554,
 765: 846634,
 766: 846652,
 767: 846656,
 768: 846743,
 769: 846760,
 770: 846764,
 771: 846811,
 772: 846823,
 773: 846830,
 774: 846833,
 775: 846959,
 776: 846986,
 777: 847023,
 778: 847025,
 779: 847049,
 780: 847066,
 781: 847071,
 782: 847127,
 783: 847139,
 784: 847149,
 785: 847174,
 786: 847186,
 787: 847207,
 788: 847232,
 789: 847241,
 790: 847260,
 791: 847277,
 792: 847302,
 793: 847344,
 794: 847374,
 795: 847434,
 796: 847573,
 797: 847631,
 798: 847634,
 799: 847677,
 800: 847703,
 801: 847738,
 802: 847790,
 803: 847803,
 804: 847853,
 805: 847901,
 806: 847962,
 807: 847980,
 808: 847982,
 809: 847989,
 810: 848029,
 811: 848071,
 812: 848107,
 813: 848154,
 814: 848270,
 815: 848319,
 816: 848329,
 817: 848471,
 818: 848605,
 819: 848631,
 820: 848681,
 821: 848761,
 822: 848765,
 823: 848832,
 824: 848846,
 825: 848878,
 826: 848970,
 827: 848988,
 828: 849003,
 829: 849018,
 830: 849032,
 831: 849066,
 832: 849082,
 833: 849090,
 834: 849098,
 835: 849100,
 836: 849110,
 837: 849129,
 838: 849152,
 839: 849202,
 840: 849205,
 841: 849250,
 842: 849257,
 843: 849274,
 844: 849297,
 845: 849330,
 846: 849414,
 847: 849466,
 848: 849469,
 849: 849470,
 850: 849505,
 851: 849515,
 852: 849520,
 853: 849559,
 854: 849578,
 855: 849589,
 856: 849590,
 857: 849618,
 858: 849697,
 859: 849713,
 860: 849756,
 861: 849809,
 862: 849870,
 863: 849871,
 864: 849886,
 865: 849901,
 866: 849931,
 867: 850004,
 868: 850020,
 869: 850028,
 870: 850058,
 871: 850072,
 872: 850102,
 873: 850133,
 874: 850139,
 875: 850240,
 876: 850281,
 877: 850290,
 878: 850529,
 879: 850533,
 880: 850562,
 881: 850564,
 882: 850601,
 883: 850645,
 884: 850652,
 885: 850656,
 886: 850676,
 887: 850679,
 888: 850743,
 889: 850768,
 890: 850801,
 891: 850807,
 892: 850834,
 893: 850925,
 894: 850961,
 895: 851066,
 896: 851101,
 897: 851129,
 898: 851146,
 899: 851147,
 900: 851188,
 901: 851231,
 902: 851241,
 903: 851287,
 904: 851291,
 905: 851343,
 906: 851394,
 907: 851447,
 908: 851468,
 909: 851515,
 910: 851528,
 911: 851569,
 912: 851644,
 913: 851675,
 914: 851676,
 915: 851683,
 916: 851716,
 917: 851722,
 918: 851819,
 919: 851865,
 920: 851903,
 921: 851913,
 922: 851952,
 923: 852014,
 924: 852015,
 925: 852065,
 926: 852080,
 927: 852145,
 928: 852163,
 929: 852180,
 930: 852181,
 931: 852182,
 932: 852202,
 933: 852235,
 934: 852303,
 935: 852333,
 936: 852360,
 937: 852437,
 938: 852452,
 939: 852521,
 940: 852540,
 941: 852572,
 942: 852600,
 943: 852650,
 944: 852690,
 945: 852793,
 946: 852846,
 947: 852853,
 948: 852856,
 949: 852863,
 950: 852940,
 951: 852975,
 952: 852998,
 953: 853037,
 954: 853038,
 955: 853041,
 956: 853091,
 957: 853099,
 958: 853109,
 959: 853119,
 960: 853121,
 961: 853124,
 962: 853127,
 963: 853172,
 964: 853197,
 965: 853210,
 966: 853221,
 967: 853235,
 968: 853354,
 969: 853429,
 970: 853448,
 971: 853522,
 972: 853529,
 973: 853548,
 974: 853553,
 975: 853607,
 976: 853622,
 977: 853643,
 978: 853887,
 979: 853927,
 980: 853998,
 981: 854042,
 982: 854133,
 983: 854190,
 984: 854261,
 985: 854270,
 986: 854329,
 987: 854354,
 988: 854373,
 989: 854385,
 990: 854405,
 991: 854483,
 992: 854496,
 993: 854539,
 994: 854589,
 995: 854607,
 996: 854677,
 997: 854716,
 998: 854731,
 999: 854754,
 ...}

In [34]:
itemid_to_id

{201704: 0,
 818981: 1,
 818996: 2,
 819063: 3,
 819112: 4,
 819115: 5,
 819210: 6,
 819255: 7,
 819304: 8,
 819308: 9,
 819330: 10,
 819400: 11,
 819487: 12,
 819518: 13,
 819534: 14,
 819578: 15,
 819590: 16,
 819594: 17,
 819612: 18,
 819765: 19,
 819840: 20,
 819845: 21,
 819849: 22,
 819927: 23,
 819969: 24,
 819978: 25,
 820011: 26,
 820082: 27,
 820122: 28,
 820291: 29,
 820296: 30,
 820301: 31,
 820321: 32,
 820347: 33,
 820352: 34,
 820429: 35,
 820486: 36,
 820518: 37,
 820551: 38,
 820582: 39,
 820612: 40,
 820701: 41,
 820752: 42,
 820788: 43,
 820895: 44,
 820923: 45,
 820950: 46,
 821007: 47,
 821025: 48,
 821032: 49,
 821083: 50,
 821134: 51,
 821174: 52,
 821200: 53,
 821209: 54,
 821219: 55,
 821316: 56,
 821324: 57,
 821344: 58,
 821464: 59,
 821465: 60,
 821556: 61,
 821565: 62,
 821695: 63,
 821741: 64,
 821761: 65,
 821787: 66,
 821788: 67,
 821825: 68,
 821845: 69,
 821863: 70,
 821890: 71,
 821895: 72,
 821923: 73,
 821930: 74,
 821970: 75,
 821974: 76,
 821976: 77,
 822049: 78,
 822066: 79,
 822073: 80,
 822101: 81,
 822115: 82,
 822140: 83,
 822161: 84,
 822178: 85,
 822225: 86,
 822226: 87,
 822236: 88,
 822259: 89,
 822346: 90,
 822348: 91,
 822407: 92,
 822517: 93,
 822524: 94,
 822558: 95,
 822646: 96,
 822739: 97,
 822781: 98,
 822785: 99,
 822812: 100,
 822860: 101,
 822892: 102,
 822941: 103,
 822944: 104,
 822953: 105,
 822965: 106,
 822966: 107,
 822970: 108,
 822985: 109,
 823031: 110,
 823098: 111,
 823099: 112,
 823176: 113,
 823194: 114,
 823255: 115,
 823266: 116,
 823356: 117,
 823365: 118,
 823475: 119,
 823503: 120,
 823530: 121,
 823565: 122,
 823576: 123,
 823641: 124,
 823646: 125,
 823687: 126,
 823704: 127,
 823709: 128,
 823721: 129,
 823767: 130,
 823775: 131,
 823790: 132,
 823862: 133,
 823915: 134,
 823990: 135,
 824005: 136,
 824037: 137,
 824072: 138,
 824073: 139,
 824074: 140,
 824122: 141,
 824180: 142,
 824193: 143,
 824209: 144,
 824255: 145,
 824291: 146,
 824303: 147,
 824305: 148,
 824311: 149,
 824396: 150,
 824546: 151,
 824593: 152,
 824605: 153,
 824758: 154,
 824759: 155,
 824789: 156,
 824796: 157,
 824813: 158,
 824846: 159,
 824915: 160,
 824923: 161,
 824931: 162,
 824970: 163,
 824977: 164,
 825006: 165,
 825118: 166,
 825123: 167,
 825153: 168,
 825170: 169,
 825176: 170,
 825180: 171,
 825208: 172,
 825218: 173,
 825226: 174,
 825289: 175,
 825295: 176,
 825313: 177,
 825317: 178,
 825326: 179,
 825343: 180,
 825365: 181,
 825412: 182,
 825494: 183,
 825538: 184,
 825541: 185,
 825550: 186,
 825556: 187,
 825616: 188,
 825621: 189,
 825625: 190,
 825659: 191,
 825665: 192,
 825670: 193,
 825703: 194,
 825731: 195,
 825748: 196,
 825749: 197,
 825751: 198,
 825850: 199,
 825882: 200,
 825970: 201,
 825976: 202,
 825994: 203,
 825999: 204,
 826004: 205,
 826067: 206,
 826090: 207,
 826099: 208,
 826120: 209,
 826144: 210,
 826239: 211,
 826265: 212,
 826272: 213,
 826385: 214,
 826419: 215,
 826566: 216,
 826571: 217,
 826580: 218,
 826597: 219,
 826666: 220,
 826695: 221,
 826784: 222,
 826816: 223,
 826830: 224,
 826835: 225,
 826842: 226,
 826860: 227,
 826900: 228,
 826952: 229,
 826984: 230,
 827024: 231,
 827047: 232,
 827050: 233,
 827079: 234,
 827133: 235,
 827175: 236,
 827180: 237,
 827261: 238,
 827271: 239,
 827332: 240,
 827361: 241,
 827373: 242,
 827393: 243,
 827394: 244,
 827546: 245,
 827570: 246,
 827578: 247,
 827631: 248,
 827656: 249,
 827667: 250,
 827671: 251,
 827683: 252,
 827749: 253,
 827781: 254,
 827802: 255,
 827806: 256,
 827911: 257,
 827919: 258,
 827999: 259,
 828048: 260,
 828055: 261,
 828073: 262,
 828106: 263,
 828114: 264,
 828143: 265,
 828219: 266,
 828278: 267,
 828283: 268,
 828328: 269,
 828331: 270,
 828370: 271,
 828385: 272,
 828393: 273,
 828412: 274,
 828437: 275,
 828490: 276,
 828516: 277,
 828557: 278,
 828588: 279,
 828713: 280,
 828732: 281,
 828867: 282,
 828901: 283,
 828935: 284,
 828993: 285,
 829001: 286,
 829116: 287,
 829138: 288,
 829266: 289,
 829278: 290,
 829291: 291,
 829323: 292,
 829349: 293,
 829427: 294,
 829456: 295,
 829491: 296,
 829495: 297,
 829515: 298,
 829550: 299,
 829563: 300,
 829617: 301,
 829621: 302,
 829645: 303,
 829662: 304,
 829685: 305,
 829722: 306,
 829802: 307,
 829823: 308,
 829852: 309,
 829866: 310,
 829920: 311,
 829928: 312,
 829950: 313,
 829955: 314,
 829958: 315,
 829972: 316,
 830015: 317,
 830070: 318,
 830097: 319,
 830125: 320,
 830156: 321,
 830202: 322,
 830203: 323,
 830245: 324,
 830304: 325,
 830374: 326,
 830503: 327,
 830526: 328,
 830582: 329,
 830615: 330,
 830677: 331,
 830686: 332,
 830701: 333,
 830775: 334,
 830783: 335,
 830790: 336,
 830795: 337,
 830850: 338,
 830887: 339,
 830935: 340,
 830941: 341,
 830965: 342,
 830973: 343,
 830976: 344,
 831063: 345,
 831091: 346,
 831124: 347,
 831125: 348,
 831161: 349,
 831181: 350,
 831223: 351,
 831246: 352,
 831296: 353,
 831331: 354,
 831371: 355,
 831390: 356,
 831407: 357,
 831509: 358,
 831545: 359,
 831557: 360,
 831559: 361,
 831587: 362,
 831628: 363,
 831712: 364,
 831728: 365,
 831763: 366,
 831888: 367,
 831937: 368,
 831965: 369,
 832001: 370,
 832007: 371,
 832207: 372,
 832221: 373,
 832249: 374,
 832270: 375,
 832285: 376,
 832288: 377,
 832335: 378,
 832373: 379,
 832394: 380,
 832442: 381,
 832473: 382,
 832492: 383,
 832513: 384,
 832526: 385,
 832544: 386,
 832678: 387,
 832746: 388,
 832760: 389,
 832768: 390,
 832785: 391,
 832828: 392,
 832937: 393,
 832976: 394,
 833014: 395,
 833025: 396,
 833151: 397,
 833155: 398,
 833169: 399,
 833193: 400,
 833238: 401,
 833241: 402,
 833273: 403,
 833347: 404,
 833351: 405,
 833383: 406,
 833436: 407,
 833458: 408,
 833494: 409,
 833577: 410,
 833583: 411,
 833591: 412,
 833598: 413,
 833648: 414,
 833724: 415,
 833754: 416,
 833841: 417,
 833849: 418,
 833866: 419,
 833870: 420,
 833940: 421,
 833969: 422,
 834009: 423,
 834086: 424,
 834102: 425,
 834117: 426,
 834129: 427,
 834158: 428,
 834303: 429,
 834382: 430,
 834391: 431,
 834396: 432,
 834399: 433,
 834435: 434,
 834465: 435,
 834491: 436,
 834516: 437,
 834565: 438,
 834572: 439,
 834631: 440,
 834662: 441,
 834715: 442,
 834777: 443,
 834826: 444,
 834833: 445,
 834842: 446,
 834846: 447,
 834911: 448,
 834915: 449,
 834932: 450,
 834952: 451,
 834962: 452,
 834993: 453,
 835004: 454,
 835017: 455,
 835028: 456,
 835058: 457,
 835077: 458,
 835080: 459,
 835098: 460,
 835236: 461,
 835243: 462,
 835247: 463,
 835278: 464,
 835279: 465,
 835285: 466,
 835296: 467,
 835300: 468,
 835347: 469,
 835394: 470,
 835431: 471,
 835476: 472,
 835482: 473,
 835499: 474,
 835530: 475,
 835558: 476,
 835578: 477,
 835595: 478,
 835604: 479,
 835616: 480,
 835618: 481,
 835619: 482,
 835675: 483,
 835715: 484,
 835783: 485,
 835796: 486,
 835819: 487,
 835943: 488,
 835973: 489,
 835977: 490,
 836043: 491,
 836085: 492,
 836090: 493,
 836163: 494,
 836258: 495,
 836286: 496,
 836423: 497,
 836445: 498,
 836645: 499,
 836703: 500,
 836745: 501,
 836758: 502,
 836891: 503,
 836916: 504,
 836924: 505,
 836952: 506,
 836964: 507,
 837005: 508,
 837012: 509,
 837073: 510,
 837107: 511,
 837139: 512,
 837167: 513,
 837242: 514,
 837270: 515,
 837304: 516,
 837339: 517,
 837366: 518,
 837413: 519,
 837495: 520,
 837527: 521,
 837561: 522,
 837569: 523,
 837579: 524,
 837602: 525,
 837644: 526,
 837647: 527,
 837664: 528,
 837669: 529,
 837677: 530,
 837684: 531,
 837720: 532,
 837751: 533,
 837864: 534,
 837865: 535,
 837908: 536,
 837969: 537,
 838010: 538,
 838050: 539,
 838097: 540,
 838136: 541,
 838186: 542,
 838210: 543,
 838261: 544,
 838319: 545,
 838347: 546,
 838369: 547,
 838396: 548,
 838554: 549,
 838563: 550,
 838571: 551,
 838602: 552,
 838637: 553,
 838712: 554,
 838733: 555,
 838738: 556,
 838739: 557,
 838797: 558,
 838829: 559,
 838842: 560,
 838859: 561,
 838867: 562,
 838882: 563,
 838971: 564,
 839035: 565,
 839094: 566,
 839112: 567,
 839152: 568,
 839162: 569,
 839188: 570,
 839191: 571,
 839192: 572,
 839208: 573,
 839225: 574,
 839243: 575,
 839248: 576,
 839262: 577,
 839346: 578,
 839419: 579,
 839438: 580,
 839485: 581,
 839605: 582,
 839653: 583,
 839656: 584,
 839747: 585,
 839766: 586,
 839818: 587,
 840173: 588,
 840227: 589,
 840244: 590,
 840255: 591,
 840322: 592,
 840386: 593,
 840566: 594,
 840601: 595,
 840609: 596,
 840640: 597,
 840732: 598,
 840735: 599,
 840764: 600,
 840890: 601,
 840938: 602,
 841016: 603,
 841025: 604,
 841035: 605,
 841159: 606,
 841220: 607,
 841223: 608,
 841228: 609,
 841236: 610,
 841266: 611,
 841287: 612,
 841309: 613,
 841327: 614,
 841443: 615,
 841469: 616,
 841478: 617,
 841584: 618,
 841606: 619,
 841683: 620,
 841686: 621,
 841762: 622,
 841872: 623,
 841899: 624,
 841905: 625,
 842068: 626,
 842091: 627,
 842125: 628,
 842140: 629,
 842170: 630,
 842249: 631,
 842264: 632,
 842286: 633,
 842350: 634,
 842368: 635,
 842385: 636,
 842392: 637,
 842407: 638,
 842416: 639,
 842423: 640,
 842434: 641,
 842455: 642,
 842470: 643,
 842474: 644,
 842522: 645,
 842530: 646,
 842558: 647,
 842647: 648,
 842698: 649,
 842704: 650,
 842707: 651,
 842762: 652,
 842769: 653,
 842783: 654,
 842795: 655,
 842886: 656,
 842930: 657,
 842995: 658,
 843013: 659,
 843111: 660,
 843114: 661,
 843116: 662,
 843127: 663,
 843171: 664,
 843206: 665,
 843239: 666,
 843259: 667,
 843306: 668,
 843338: 669,
 843339: 670,
 843346: 671,
 843361: 672,
 843376: 673,
 843418: 674,
 843441: 675,
 843450: 676,
 843464: 677,
 843558: 678,
 843567: 679,
 843656: 680,
 843689: 681,
 843728: 682,
 843744: 683,
 843756: 684,
 843819: 685,
 843891: 686,
 843898: 687,
 843911: 688,
 843929: 689,
 843951: 690,
 844054: 691,
 844155: 692,
 844165: 693,
 844166: 694,
 844169: 695,
 844175: 696,
 844179: 697,
 844278: 698,
 844282: 699,
 844413: 700,
 844424: 701,
 844441: 702,
 844462: 703,
 844493: 704,
 844498: 705,
 844652: 706,
 844697: 707,
 844740: 708,
 844748: 709,
 844759: 710,
 844818: 711,
 844839: 712,
 844929: 713,
 844991: 714,
 845052: 715,
 845053: 716,
 845078: 717,
 845082: 718,
 845091: 719,
 845109: 720,
 845163: 721,
 845193: 722,
 845196: 723,
 845208: 724,
 845265: 725,
 845294: 726,
 845307: 727,
 845319: 728,
 845348: 729,
 845370: 730,
 845379: 731,
 845432: 732,
 845462: 733,
 845622: 734,
 845675: 735,
 845677: 736,
 845705: 737,
 845715: 738,
 845774: 739,
 845868: 740,
 845894: 741,
 845896: 742,
 845914: 743,
 845975: 744,
 845992: 745,
 846014: 746,
 846015: 747,
 846032: 748,
 846043: 749,
 846045: 750,
 846114: 751,
 846202: 752,
 846270: 753,
 846285: 754,
 846301: 755,
 846334: 756,
 846380: 757,
 846417: 758,
 846429: 759,
 846466: 760,
 846482: 761,
 846502: 762,
 846550: 763,
 846554: 764,
 846634: 765,
 846652: 766,
 846656: 767,
 846743: 768,
 846760: 769,
 846764: 770,
 846811: 771,
 846823: 772,
 846830: 773,
 846833: 774,
 846959: 775,
 846986: 776,
 847023: 777,
 847025: 778,
 847049: 779,
 847066: 780,
 847071: 781,
 847127: 782,
 847139: 783,
 847149: 784,
 847174: 785,
 847186: 786,
 847207: 787,
 847232: 788,
 847241: 789,
 847260: 790,
 847277: 791,
 847302: 792,
 847344: 793,
 847374: 794,
 847434: 795,
 847573: 796,
 847631: 797,
 847634: 798,
 847677: 799,
 847703: 800,
 847738: 801,
 847790: 802,
 847803: 803,
 847853: 804,
 847901: 805,
 847962: 806,
 847980: 807,
 847982: 808,
 847989: 809,
 848029: 810,
 848071: 811,
 848107: 812,
 848154: 813,
 848270: 814,
 848319: 815,
 848329: 816,
 848471: 817,
 848605: 818,
 848631: 819,
 848681: 820,
 848761: 821,
 848765: 822,
 848832: 823,
 848846: 824,
 848878: 825,
 848970: 826,
 848988: 827,
 849003: 828,
 849018: 829,
 849032: 830,
 849066: 831,
 849082: 832,
 849090: 833,
 849098: 834,
 849100: 835,
 849110: 836,
 849129: 837,
 849152: 838,
 849202: 839,
 849205: 840,
 849250: 841,
 849257: 842,
 849274: 843,
 849297: 844,
 849330: 845,
 849414: 846,
 849466: 847,
 849469: 848,
 849470: 849,
 849505: 850,
 849515: 851,
 849520: 852,
 849559: 853,
 849578: 854,
 849589: 855,
 849590: 856,
 849618: 857,
 849697: 858,
 849713: 859,
 849756: 860,
 849809: 861,
 849870: 862,
 849871: 863,
 849886: 864,
 849901: 865,
 849931: 866,
 850004: 867,
 850020: 868,
 850028: 869,
 850058: 870,
 850072: 871,
 850102: 872,
 850133: 873,
 850139: 874,
 850240: 875,
 850281: 876,
 850290: 877,
 850529: 878,
 850533: 879,
 850562: 880,
 850564: 881,
 850601: 882,
 850645: 883,
 850652: 884,
 850656: 885,
 850676: 886,
 850679: 887,
 850743: 888,
 850768: 889,
 850801: 890,
 850807: 891,
 850834: 892,
 850925: 893,
 850961: 894,
 851066: 895,
 851101: 896,
 851129: 897,
 851146: 898,
 851147: 899,
 851188: 900,
 851231: 901,
 851241: 902,
 851287: 903,
 851291: 904,
 851343: 905,
 851394: 906,
 851447: 907,
 851468: 908,
 851515: 909,
 851528: 910,
 851569: 911,
 851644: 912,
 851675: 913,
 851676: 914,
 851683: 915,
 851716: 916,
 851722: 917,
 851819: 918,
 851865: 919,
 851903: 920,
 851913: 921,
 851952: 922,
 852014: 923,
 852015: 924,
 852065: 925,
 852080: 926,
 852145: 927,
 852163: 928,
 852180: 929,
 852181: 930,
 852182: 931,
 852202: 932,
 852235: 933,
 852303: 934,
 852333: 935,
 852360: 936,
 852437: 937,
 852452: 938,
 852521: 939,
 852540: 940,
 852572: 941,
 852600: 942,
 852650: 943,
 852690: 944,
 852793: 945,
 852846: 946,
 852853: 947,
 852856: 948,
 852863: 949,
 852940: 950,
 852975: 951,
 852998: 952,
 853037: 953,
 853038: 954,
 853041: 955,
 853091: 956,
 853099: 957,
 853109: 958,
 853119: 959,
 853121: 960,
 853124: 961,
 853127: 962,
 853172: 963,
 853197: 964,
 853210: 965,
 853221: 966,
 853235: 967,
 853354: 968,
 853429: 969,
 853448: 970,
 853522: 971,
 853529: 972,
 853548: 973,
 853553: 974,
 853607: 975,
 853622: 976,
 853643: 977,
 853887: 978,
 853927: 979,
 853998: 980,
 854042: 981,
 854133: 982,
 854190: 983,
 854261: 984,
 854270: 985,
 854329: 986,
 854354: 987,
 854373: 988,
 854385: 989,
 854405: 990,
 854483: 991,
 854496: 992,
 854539: 993,
 854589: 994,
 854607: 995,
 854677: 996,
 854716: 997,
 854731: 998,
 854754: 999,
 ...}

In [22]:
user_features

,age_desc,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,user_id,bill_avg,week_last_bill,items_per_week
0,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1,2.492077,95,18.264368
1,45-54,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7,2.673405,95,11.780220
2,25-34,U,25-34K,Unknown,2 Adults Kids,3,1,8,2.798250,95,20.505882
3,25-34,U,75-99K,Homeowner,2 Adults Kids,4,2,13,5.693402,95,26.750000
4,45-54,B,50-74K,Homeowner,Single Female,1,None/Unknown,16,2.927602,94,6.412500
...,...,...,...,...,...,...,...,...,...,...,...
796,35-44,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2494,3.560885,93,6.230769
797,45-54,A,75-99K,Homeowner,Unknown,3,1,2496,2.891049,95,18.205128
798,45-54,U,35-49K,Unknown,Single Male,1,None/Unknown,2497,3.533885,95,23.349398
799,25-34,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2498,3.012473,95,10.544304
800,25-34,U,Under 15K,Unknown,2 Adults Kids,3,1,2499,2.966347,92,11.535714

In [20]:
user_feat = pd.DataFrame(user_item_matrix.index)
user_feat

      user_id
0           1
1           2
2           3
3           4
4           5
...       ...
2494     2496
2495     2497
2496     2498
2497     2499
2498     2500

[2499 rows x 1 columns]

In [22]:
user_feat = user_feat.merge(user_features, on='user_id', how='left')
user_feat

,user_id,age_desc,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,bill_avg,week_last_bill,items_per_week
0,1,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,2.492077,95.0,18.264368
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2494,2496,45-54,A,75-99K,Homeowner,Unknown,3,1,2.891049,95.0,18.205128
2495,2497,45-54,U,35-49K,Unknown,Single Male,1,None/Unknown,3.533885,95.0,23.349398
2496,2498,25-34,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,3.012473,95.0,10.544304
2497,2499,25-34,U,Under 15K,Unknown,2 Adults Kids,3,1,2.966347,92.0,11.535714
2498,2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
user_feat.set_index('user_id', inplace=True)
user_feat

,age_desc,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,bill_avg,week_last_bill,items_per_week
user_id,,,,,,,,,,
1,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,2.492077,95.0,18.264368
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2496,45-54,A,75-99K,Homeowner,Unknown,3,1,2.891049,95.0,18.205128
2497,45-54,U,35-49K,Unknown,Single Male,1,None/Unknown,3.533885,95.0,23.349398
2498,25-34,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,3.012473,95.0,10.544304
2499,25-34,U,Under 15K,Unknown,2 Adults Kids,3,1,2.966347,92.0,11.535714
2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
user_feat = user_feat.fillna("")
user_feat

,age_desc,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,bill_avg,week_last_bill,items_per_week
user_id,,,,,,,,,,
1,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,2.492077,95.0,18.264368
2,,,,,,,,,,
3,,,,,,,,,,
4,,,,,,,,,,
5,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...
2496,45-54,A,75-99K,Homeowner,Unknown,3,1,2.891049,95.0,18.205128
2497,45-54,U,35-49K,Unknown,Single Male,1,None/Unknown,3.533885,95.0,23.349398
2498,25-34,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,3.012473,95.0,10.544304
2499,25-34,U,Under 15K,Unknown,2 Adults Kids,3,1,2.966347,92.0,11.535714
2500,,,,,,,,,,

In [39]:
data['week_no'].max()

95

### Cхема обучения и валидации

In [ ]:
# -- давние покупки -- | -- 6 недель -- | -- 3 недель -- 
# подобрать размер 2-ого датасета (6 недель) --> learning curve (зависимость метрики recall@k от размера датасета)
val_lvl_1_size_weeks = 6
val_lvl_2_size_weeks = 3

data_train_lvl_1 = data[data[''] < data['week_no'].max() - (val_lvl_1_size_weeks + val_lvl_2_size_weeks)]
data_val_lvl_1 = data[(data['week_no'] >= data['week_no'].max() - (val_lvl_1_size_weeks + val_lvl_2_size_weeks)) &
                      (data['week_no'] < data['week_no'].max() - (val_lvl_2_size_weeks))]

data_train_lvl_2 = data_val_lvl_1.copy()  # Для наглядности. Далее мы добавим изменения, и они будут отличаться
data_val_lvl_2 = data[data['week_no'] >= data['week_no'].max() - val_lvl_2_size_weeks]

Провнряем правильность разбиения по неделям

In [44]:
data_train_lvl_1['week_no'].min(), data_train_lvl_1['week_no'].max()

(1, 85)

In [45]:
data_val_lvl_1['week_no'].min(), data_val_lvl_1['week_no'].max()

(86, 91)

In [46]:
data_train_lvl_2['week_no'].min(), data_train_lvl_2['week_no'].max()

(86, 91)

In [47]:
data_val_lvl_2['week_no'].min(), data_val_lvl_2['week_no'].max()

(92, 95)

Создаем экземпляр класса MainRecommender

In [27]:
recommender = MainRecommender(data_train_lvl_1, item_features, user_features)

user_item_matrix
user_feat
item_feat

WARNING:root:Intel MKL BLAS detected. Its highly recommend to set the environment variable 'export MKL_NUM_THREADS=1' to disable its internal multithreading

ALS model
ALS TF-IDF model
ALS BM25 model
LightFM model
Own

In [94]:
users_lvl_2_pred_als = pd.DataFrame(data_val_lvl_2['user_id'].unique())
users_lvl_2_pred_als

         0
0      338
1     2120
2     2324
3      514
4     1762
...    ...
2037  1386
2038   472
2039    90
2040  1635
2041   832

[2042 rows x 1 columns]

In [117]:
users_lvl_2_pred_als.columns = ['user_id']
users_lvl_2_pred_als

      user_id
0         338
1        2120
2        2324
3         514
4        1762
...       ...
2037     1386
2038      472
2039       90
2040     1635
2041      832

[2042 rows x 1 columns]

In [116]:
result_lvl_2 = data_val_lvl_2.groupby('user_id')['item_id'].unique().reset_index()
result_lvl_2.columns=['user_id', 'actual']

In [48]:
result_lvl_2 = data_val_lvl_2.groupby('user_id')['item_id'].unique().reset_index()
result_lvl_2.columns=['user_id', 'actual']
result_lvl_2

      user_id                                             actual
0           1  [999999, 856942, 865456, 907957, 914190, 94331...
1           3  [835476, 999999, 920626, 958154, 1053690, 1096...
2           6  [999999, 1006718, 1104227, 1108624, 1110392, 8...
3           7  [840386, 999999, 898068, 909714, 993838, 10031...
4           8  [835098, 872137, 910439, 924610, 992977, 99999...
...       ...                                                ...
2037     2496                                           [999999]
2038     2497  [1016709, 9835695, 999999, 845294, 871756, 873...
2039     2498  [999999, 901776, 914190, 958382, 972437, 10398...
2040     2499  [867188, 877580, 902396, 914190, 951590, 95813...
2041     2500  [852182, 856345, 923746, 948670, 1018007, 1044...

[2042 rows x 2 columns]

In [124]:
k_n = 5
num = 40

In [50]:
popularity = data.groupby('item_id')['quantity'].sum().reset_index()
popularity

        item_id  quantity
0        201704        53
1        818981        69
2        818996        24
3        819063       224
4        819112        82
...         ...       ...
12739  17169131        23
12740  17179856        16
12741  17179873        16
12742  17208470        45
12743  17214946        19

[12744 rows x 2 columns]

In [51]:
popularity.rename(columns={'quantity': 'n_sold'}, inplace=True)
popularity

        item_id  n_sold
0        201704      53
1        818981      69
2        818996      24
3        819063     224
4        819112      82
...         ...     ...
12739  17169131      23
12740  17179856      16
12741  17179873      16
12742  17208470      45
12743  17214946      19

[12744 rows x 2 columns]

In [53]:
popularity.sort_values('n_sold', ascending=False).head(num+1)

      item_id     n_sold
4964   999999  239310436
4804   995242      13491
5773  1029743       9598
8551  1133018       7478
4439   981760       6737
7840  1106523       6583
8400  1127831       5310
8906  5569230       4669
2485   908531       4541
3670   951590       4284
1203   862349       4104
2695   916122       4008
6546  1058997       4002
6146  1044078       3898
8369  1126899       3275
3937   961554       3169
697    844179       3138
1123   859075       3132
5107  1005186       3108
2344   904360       3030
6703  1065593       3016
6857  1070820       2951
693    844165       2903
2902   923746       2899
6406  1053690       2867
8917  5569471       2600
7547  1096036       2555
2655   914190       2517
1001   854852       2447
2319   903325       2372
1652   878996       2301
5095  1004906       2277
3960   962229       2262
4562   986912       2257
1312   866211       2253
7432  1092026       2170
3967   962568       2169
9949  8090521       2072
7149  1081177       2035
9953  8090537       1991
5622  1024306       1892

In [56]:
item_list = popularity.sort_values('n_sold', ascending=False).head(num+1).item_id.tolist()
item_list

[999999,
 995242,
 1029743,
 1133018,
 981760,
 1106523,
 1127831,
 5569230,
 908531,
 951590,
 862349,
 916122,
 1058997,
 1044078,
 1126899,
 961554,
 844179,
 859075,
 1005186,
 904360,
 1065593,
 1070820,
 844165,
 923746,
 1053690,
 5569471,
 1096036,
 914190,
 854852,
 903325,
 878996,
 1004906,
 962229,
 986912,
 866211,
 1092026,
 962568,
 8090521,
 1081177,
 8090537,
 1024306]

In [69]:
len(item_list)

40

In [70]:
item_list = item_list[1:num+1]
item_list

[1029743,
 1133018,
 981760,
 1106523,
 1127831,
 5569230,
 908531,
 951590,
 862349,
 916122,
 1058997,
 1044078,
 1126899,
 961554,
 844179,
 859075,
 1005186,
 904360,
 1065593,
 1070820,
 844165,
 923746,
 1053690,
 5569471,
 1096036,
 914190,
 854852,
 903325,
 878996,
 1004906,
 962229,
 986912,
 866211,
 1092026,
 962568,
 8090521,
 1081177,
 8090537,
 1024306]

In [59]:
# Подготовим список наиболее покупаемых товаров
popularity = data.groupby('item_id')['quantity'].sum().reset_index()
popularity.rename(columns={'quantity': 'n_sold'}, inplace=True)
item_list = popularity.sort_values('n_sold', ascending=False).head(num+1).item_id.tolist()
item_list = item_list[1:num+1]
len(item_list)

40

Проводим локальную проверку работоспособности модели ALS

In [71]:
n_factors, regularization, iterations, num_threads =50, 0.0001, 15, 4

In [74]:
from implicit.als import AlternatingLeastSquares

In [75]:
model = AlternatingLeastSquares(factors=n_factors,
                                        regularization=regularization,
                                        iterations=iterations,
                                        num_threads=num_threads)
model.fit(csr_matrix(user_item_matrix).T.tocsr(), show_progress=False)

In [76]:
model.recommend(userid=userid_to_id[1], 
                                             user_items=csr_matrix(user_item_matrix).tocsr(),   # на вход user-item matrix
                                             N=5, 
                                             filter_already_liked_items=False, 
                                             filter_items=[itemid_to_id[999999]],  # !!! 
                                             recalculate_user=True)

[(1826, 1.089351418887143),
 (4804, 1.061091063779555),
 (9059, 0.9991109451136332),
 (2344, 0.9898791262291128),
 (8912, 0.9380612761971857)]

In [80]:
user = 1
rec_num = 5
[id_to_itemid[rec[0]] for rec in 
                        model.recommend(userid=userid_to_id[user], 
                                             user_items=csr_matrix(user_item_matrix).tocsr(),   # на вход user-item matrix
                                             N= rec_num, 
                                             filter_already_liked_items=False, 
                                             filter_items=[itemid_to_id[999999]],  # !!! 
                                             recalculate_user=True)]

[885290, 995242, 5978656, 904360, 5569374]

In [84]:
itemid_to_id[995242]

4804

In [ ]:
Вроде все в порядке

Готовим подпрограммы для трейна первого уровня

In [86]:
user_train_list = data_train_lvl_1["user_id"].unique().tolist()
user_train_list[:3]

[2375, 1364, 1130]

In [103]:
def get_pred_als(recommender, user_train_list, item_list, x, num=5):
    res = []
    if x in user_train_list:
        res.extend(recommender.get_als_recommendations(x, rec_num=num))
    else:
        res.extend(item_list)    # res.extend(random.choices(item_list, k=num))
    return res

In [104]:
def get_pred_als_tfidf(recommender, user_train_list, item_list, x, num=5):
    res = []
    if x in user_train_list:
        res.extend(recommender.get_als_tfidf_recommendations(x, rec_num=num))
    else:
        res.extend(item_list)    # res.extend(random.choices(item_list, k=num))
    return res

In [105]:
def get_pred_als_bm25(recommender, user_train_list, item_list, x, num=5):
    res = []
    if x in user_train_list:
        res.extend(recommender.get_als_bm25_recommendations(x, rec_num=num))
    else:
        res.extend(item_list)    # res.extend(random.choices(item_list, k=num))
    return res

In [106]:
def get_pred_own(recommender, user_train_list, item_list, x, num=5):
    res = []
    if x in user_train_list:
        res.extend(recommender.get_own_recommendations(x, rec_num=num))
    else:
        res.extend(item_list)    # res.extend(random.choices(item_list, k=num))
    return res

In [107]:
def get_pred_similar_items(recommender, user_train_list, item_list, x, num=5):
    res = []
    if x in user_train_list:
        res.extend(recommender.get_similar_items_recommendation(x, rec_num=num))
    else:
        res.extend(item_list)    # res.extend(random.choices(item_list, k=num))
    return res

Код для запуска рекомендаций  топ-N товаров и расчета метрики precision_at_k

In [ ]:
users_lvl_2_pred_als['predictions'] = users_lvl_2_pred_als['user_id'].apply(\
                            lambda x: get_pred_als(recommender, user_train_list, item_list, x, num=num))
    
users_lvl_2_pred_als["prec"] = users_lvl_2_pred_als['user_id'].apply(\
        lambda x: precision_at_k(users_lvl_2_pred_als.loc[users_lvl_2_pred_als["user_id"] == x, "predictions"].values[0], 
                                 list(result_lvl_2.loc[result_lvl_2["user_id"] == x, "actual"].values[0]), 
                                 k=k_n))

users_lvl_2_pred_als["prec"].mean()

### РАСЧЕТ ЗАВИС!!!
### Видимо, у меня слабый компьютер.
### Поэтому решил уменьшить количество пользователей до 500
(users_lvl_2_pred_als_part)

In [118]:
users_lvl_2_pred_als

      user_id
0         338
1        2120
2        2324
3         514
4        1762
...       ...
2037     1386
2038      472
2039       90
2040     1635
2041      832

[2042 rows x 1 columns]

In [156]:
# Делаем выборку 500 пользователей
users_lvl_2_pred_als_part = users_lvl_2_pred_als.head(500)
users_lvl_2_pred_als_part

     user_id
0        338
1       2120
2       2324
3        514
4       1762
..       ...
495     2425
496      511
497     1020
498     1146
499      986

[500 rows x 1 columns]

In [170]:
# Осуществляем подгонку валидационного датафрейма по 500 пользователям
result_lvl_2_part = result_lvl_2.loc[result_lvl_2['user_id'].\
                                 isin(users_lvl_2_pred_als_part['user_id']. tolist ())]

In [157]:
# Считаем предсказания
users_lvl_2_pred_als_part['predictions'] = users_lvl_2_pred_als_part['user_id'] \
.apply(lambda x: get_pred_als(recommender, user_train_list, item_list, x, num=num))

In [158]:
# Проверяем срабатывание
users_lvl_2_pred_als_part

     user_id                                        predictions
0        338  [1037863, 845208, 1026118, 1133018, 904360, 98...
1       2120  [1106523, 1029743, 995242, 981760, 1058997, 11...
2       2324  [995242, 1029743, 5978656, 981760, 961554, 112...
3        514  [878996, 1127831, 866211, 1005186, 1024306, 10...
4       1762  [1114597, 1003188, 1068719, 961554, 1110572, 9...
..       ...                                                ...
495     2425  [1029743, 995242, 981760, 904360, 854852, 1127...
496      511  [1133018, 1106523, 1044078, 981760, 1038217, 9...
497     1020  [1004906, 1037863, 862349, 995242, 916122, 961...
498     1146  [1133018, 904360, 6533765, 1033615, 1005186, 1...
499      986  [1029743, 995242, 908531, 5569230, 1038217, 10...

[500 rows x 2 columns]

## У меня не получилось обратиться к файлу с метриками 

### Я так понял, что при импорте функции с метрикой, почему то не учитывается подключение библиотеки "import numpy as np"

### Поэтому перенс метрики в этот файл.

In [151]:
def precision_at_k(recommended_list, bought_list, k=5):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    bought_list = bought_list  # Тут нет [:k] !!
    recommended_list = recommended_list[:k]
    
    flags = np.isin(bought_list, recommended_list)
    precision = flags.sum() / len(recommended_list)
    
    
    return precision

In [171]:
# Считаем метрику precision_at_k для выборки из 500 пользователей
users_lvl_2_pred_als_part["prec"] = users_lvl_2_pred_als_part['user_id'].apply(\
        lambda x: precision_at_k((users_lvl_2_pred_als_part.loc[users_lvl_2_pred_als_part["user_id"] == x, "predictions"].values[0]), 
                                 (result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "actual"].values[0]), 
                                 k=k_n))

In [172]:
users_lvl_2_pred_als_part

     user_id                                        predictions  prec
0        338  [1037863, 845208, 1026118, 1133018, 904360, 98...   0.6
1       2120  [1106523, 1029743, 995242, 981760, 1058997, 11...   0.0
2       2324  [995242, 1029743, 5978656, 981760, 961554, 112...   0.6
3        514  [878996, 1127831, 866211, 1005186, 1024306, 10...   0.6
4       1762  [1114597, 1003188, 1068719, 961554, 1110572, 9...   0.2
..       ...                                                ...   ...
495     2425  [1029743, 995242, 981760, 904360, 854852, 1127...   0.2
496      511  [1133018, 1106523, 1044078, 981760, 1038217, 9...   0.0
497     1020  [1004906, 1037863, 862349, 995242, 916122, 961...   0.8
498     1146  [1133018, 904360, 6533765, 1033615, 1005186, 1...   0.6
499      986  [1029743, 995242, 908531, 5569230, 1038217, 10...   0.2

[500 rows x 3 columns]

In [173]:
users_lvl_2_pred_als_part["prec"].mean()

0.23600000000000085

In [175]:
def recall_at_k(recommended_list, bought_list, k=5):
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]
    
    flags = np.isin(bought_list, recommended_list)
    
    recall = flags.sum() / len(bought_list)
    
    return recall

In [176]:
# Считаем метрику recall_at_k для выборки из 500 пользователей
users_lvl_2_pred_als_part["rec"] = users_lvl_2_pred_als_part['user_id'].apply(\
        lambda x: recall_at_k((users_lvl_2_pred_als_part.loc[users_lvl_2_pred_als_part["user_id"] == x, "predictions"].values[0]), 
                                 (result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "actual"].values[0]), 
                                 k=k_n))

In [177]:
users_lvl_2_pred_als_part["rec"].mean()

0.03179968066943935

Код для запуска рекомендаций  топ-N товаров с учетом представления tfidf и расчета метрик

In [178]:
users_lvl_2_pred_als_part['predictions_tfidf'] = users_lvl_2_pred_als_part['user_id'].apply(\
                            lambda x: get_pred_als_tfidf(recommender, user_train_list, item_list, x, num=num))

In [179]:
# Считаем метрику precision_at_k для выборки из 500 пользователей
users_lvl_2_pred_als_part["prec_tfidf"] = users_lvl_2_pred_als_part['user_id'].apply(\
        lambda x: precision_at_k((users_lvl_2_pred_als_part.loc[users_lvl_2_pred_als_part["user_id"] == x, "predictions_tfidf"].values[0]), 
                                 (result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "actual"].values[0]), 
                                 k=k_n))

In [181]:
users_lvl_2_pred_als_part["prec_tfidf"].mean()

0.17160000000000067

In [182]:
# Считаем метрику recall_at_k для выборки из 500 пользователей
users_lvl_2_pred_als_part["rec_tfidf"] = users_lvl_2_pred_als_part['user_id'].apply(\
        lambda x: recall_at_k((users_lvl_2_pred_als_part.loc[users_lvl_2_pred_als_part["user_id"] == x, "predictions_tfidf"].values[0]), 
                                 (result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "actual"].values[0]), 
                                 k=k_n))

users_lvl_2_pred_als_part["rec_tfidf"].mean()

0.022713076586009944

Код для запуска рекомендаций  топ-N товаров с учетом представления bm25 и расчета метрик

In [183]:
users_lvl_2_pred_als_part['predictions_bm25'] = users_lvl_2_pred_als_part['user_id'].apply(\
                            lambda x: get_pred_als_tfidf(recommender, user_train_list, item_list, x, num=num))

In [186]:
# Считаем метрику precision_at_k для выборки из 500 пользователей
users_lvl_2_pred_als_part["prec_bm25"] = users_lvl_2_pred_als_part['user_id'].apply(\
        lambda x: precision_at_k((users_lvl_2_pred_als_part.loc[users_lvl_2_pred_als_part["user_id"] == x, "predictions_bm25"].values[0]), 
                                 (result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "actual"].values[0]), 
                                 k=k_n))
users_lvl_2_pred_als_part["prec_bm25"].mean()

0.17160000000000067

In [187]:
# Считаем метрику recall_at_k для выборки из 500 пользователей
users_lvl_2_pred_als_part["rec_bm25"] = users_lvl_2_pred_als_part['user_id'].apply(\
        lambda x: recall_at_k((users_lvl_2_pred_als_part.loc[users_lvl_2_pred_als_part["user_id"] == x, "predictions_bm25"].values[0]), 
                                 (result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "actual"].values[0]), 
                                 k=k_n))

users_lvl_2_pred_als_part["rec_tfidf"].mean()

0.022713076586009944

In [188]:
# Просматриваем получившийся датафрейм
users_lvl_2_pred_als_part.head()

,user_id,predictions,prec,rec,predictions_tfidf,prec_tfidf,rec_tfidf,predictions_bm25,,prec_bm25,rec_bm25
0,338,"[1037863, 845208, 1026118, 1133018, 904360, 98...",0.6,0.042857,"[845208, 1026118, 1037863, 904360, 1081177, 98...",0.4,0.028571,"[845208, 1026118, 1037863, 904360, 1081177, 98...",0.4,0.4,0.028571
1,2120,"[1106523, 1029743, 995242, 981760, 1058997, 11...",0.0,0.000000,"[1029743, 995242, 981760, 1127831, 1106523, 11...",0.0,0.000000,"[1029743, 995242, 981760, 1127831, 1106523, 11...",0.0,0.0,0.000000
2,2324,"[995242, 1029743, 5978656, 981760, 961554, 112...",0.6,0.076923,"[1005186, 5978656, 1058997, 5569230, 1136257, ...",0.2,0.025641,"[1005186, 5978656, 1058997, 5569230, 1136257, ...",0.2,0.2,0.025641
3,514,"[878996, 1127831, 866211, 1005186, 1024306, 10...",0.6,0.096774,"[1062002, 1105488, 1127179, 878996, 1023720, 8...",0.4,0.064516,"[1062002, 1105488, 1127179, 878996, 1023720, 8...",0.4,0.4,0.064516
4,1762,"[1114597, 1003188, 1068719, 961554, 1110572, 9...",0.2,0.012346,"[1084331, 1003188, 1065593, 1136257, 976199, 1...",0.4,0.024691,"[1084331, 1003188, 1065593, 1136257, 976199, 1...",0.4,0.4,0.024691

In [30]:
users_lvl_2_pred_als.head()

   user_id  ...  rec_bm25
0      338  ...  0.013889
1     2120  ...  0.000000
2     2324  ...  0.025000
3      514  ...  0.125000
4     1762  ...  0.012048

[5 rows x 10 columns]

### ВЫВОД: лучшую модель показала чистая АLS (не tfidf и не bm25).

### Целевая метрика precision@5 получилась равной 0.23.

### Будем использовать ALS в качестве входной для классификатора второго уровня LGBMClassifier

## LGBMClassifier

### Строим классификатор

In [190]:
data_train_lvl_2.head()

,user_id,basket_id,day,item_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc
2104867,2070,40618492260,594,999999,1,1.00,311,-0.29,40,86,0.0,0.0
2107468,2021,40618753059,594,999999,1,0.99,443,0.00,101,86,0.0,0.0
2107469,2021,40618753059,594,856060,1,1.77,443,-0.09,101,86,0.0,0.0
2107470,2021,40618753059,594,869344,1,1.67,443,-0.22,101,86,0.0,0.0
2107471,2021,40618753059,594,896862,2,5.00,443,-2.98,101,86,0.0,0.0

In [192]:
users_lvl_2 = pd.DataFrame(data_train_lvl_2['user_id'].unique())
users_lvl_2.columns = ['user_id']
users_lvl_2

      user_id
0        2070
1        2021
2        1753
3        2120
4        1346
...       ...
2149     1446
2150     1784
2151      436
2152     1697
2153     1745

[2154 rows x 1 columns]

In [ ]:
users_lvl_2['candidates'] = users_lvl_2['user_id'].apply\
(lambda x: get_pred_als(recommender, user_train_list, item_list, x, num=num))

### РАСЧЕТ ОПЯТЬ ЗАВИС!!!
### Видимо, у меня слабый компьютер.
### Поэтому решил уменьшить количество пользователей до 500
(users_lvl_2_pred_als_part)

In [193]:
users_lvl_2_part = users_lvl_2.head(500)
users_lvl_2_part

     user_id
0       2070
1       2021
2       1753
3       2120
4       1346
..       ...
495     2149
496      491
497      378
498      603
499     1388

[500 rows x 1 columns]

In [194]:
# Считаем предсказания
users_lvl_2_part['predictions'] = users_lvl_2_part['user_id'] \
.apply(lambda x: get_pred_als(recommender, user_train_list, item_list, x, num=num))

In [195]:
users_lvl_2_part.head()

   user_id                                        predictions
0     2070  [923746, 1029743, 1044078, 1096036, 896369, 10...
1     2021  [951590, 981760, 1044078, 904360, 844179, 1029...
2     1753  [1005186, 879755, 1085604, 986912, 1106523, 11...
3     2120  [1106523, 1029743, 995242, 981760, 1058997, 11...
4     1346  [1127831, 1058997, 1126899, 866211, 878996, 98...

In [199]:
users_lvl_2_part.rename(columns={'predictions': 'candidates'}, inplace=True)
users_lvl_2_part.head()

   user_id                                         candidates
0     2070  [923746, 1029743, 1044078, 1096036, 896369, 10...
1     2021  [951590, 981760, 1044078, 904360, 844179, 1029...
2     1753  [1005186, 879755, 1085604, 986912, 1106523, 11...
3     2120  [1106523, 1029743, 995242, 981760, 1058997, 11...
4     1346  [1127831, 1058997, 1126899, 866211, 878996, 98...

In [200]:
# Т.к. очень долго считается, сохраним файл
users_lvl_2_part.to_csv("./prep12/users_lvl_2_part.csv", index=False)

In [207]:
users_lvl_2_part.candidates[0][:10]

[923746,
 1029743,
 1044078,
 1096036,
 896369,
 1005186,
 981760,
 910032,
 859075,
 833025]

In [212]:
# Проверим еще раз на пропуски
users_lvl_2_part.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     500 non-null    int64
 1   candidates  500 non-null    object
dtypes: int64(1), object(1)
memory usage: 7.9+ KB

In [216]:
users_lvl_2_part.candidates.values

array([list([923746, 1029743, 1044078, 1096036, 896369, 1005186, 981760, 910032, 859075, 833025, 871756, 893018, 908531, 1107553, 1038217, 1106523, 5568378, 1006184, 1068719, 1133018, 904360, 1042438, 1127831, 1085604, 1024306, 878996, 909894, 847982, 1070015, 1062966, 995242, 866211, 899624, 962568, 1043590, 865456, 961554, 1056509, 965267, 879755]),
       list([951590, 981760, 1044078, 904360, 844179, 1029743, 995242, 845208, 1004906, 923746, 1106523, 1037863, 1133018, 962229, 1081177, 1127831, 910032, 871756, 1096036, 1068719, 847982, 9527290, 859075, 1043590, 866211, 909894, 854852, 9526410, 5592931, 916122, 899624, 12301109, 1065593, 883932, 987562, 952163, 1062966, 944534, 1039156, 965766]),
       list([1005186, 879755, 1085604, 986912, 1106523, 1133018, 1110572, 1110843, 1065593, 5978656, 1037894, 861445, 844165, 859075, 863802, 8090537, 1091365, 1075368, 1107553, 5569230, 981760, 1053690, 5568378, 1092026, 979707, 859237, 908531, 1136257, 8090521, 1068719, 901543, 1106301, 1076056, 1044078, 5978648, 882305, 922907, 1007136, 5592931, 897125]),
       list([1106523, 1029743, 995242, 981760, 1058997, 1126899, 1133018, 1127831, 5569230, 1053690, 1070820, 986912, 844165, 1016800, 1044078, 1005186, 917033, 878996, 854852, 1085604, 5568378, 916122, 1065593, 5569471, 904360, 914190, 951590, 12523928, 866211, 1036347, 862349, 953539, 1118946, 1122568, 930118, 1033615, 7168026, 1007136, 1092026, 1110843]),
       list([1127831, 1058997, 1126899, 866211, 878996, 981760, 1024306, 961554, 903325, 5978656, 1023720, 909714, 962568, 901062, 916122, 854852, 1105488, 930118, 965267, 5978648, 1022254, 6034857, 1062002, 904360, 1117514, 933637, 1057102, 1051516, 1127179, 860299, 5569471, 951412, 1055504, 1006184, 1081177, 995242, 7024990, 970030, 1098248, 857503]),
       list([995242, 1029743, 5978656, 981760, 961554, 1127831, 916122, 5978648, 5569230, 854852, 6034857, 903325, 909714, 824005, 1057260, 904360, 866211, 1136257, 908531, 1039156, 844179, 878996, 979707, 914190, 1117514, 5569471, 859075, 1027569, 1119051, 962568, 1058997, 1004906, 901062, 1081177, 970030, 995965, 897125, 8090521, 845208, 923746]),
       list([981760, 995242, 859075, 951590, 1127831, 908531, 5978656, 1029743, 1058997, 1126899, 904360, 5569230, 866211, 923746, 1004906, 961554, 1039156, 5978648, 854852, 1133018, 987562, 916122, 1024306, 909894, 878996, 1044078, 845208, 845193, 962568, 933835, 1101010, 910032, 1081177, 1096036, 1040807, 5569471, 1018740, 979707, 1038217, 1053690]),
       list([1081177, 1065593, 981760, 1053690, 995242, 951590, 1075368, 1133018, 909894, 1026118, 933835, 904360, 961554, 893501, 854852, 1106523, 962229, 1040807, 962568, 1043301, 1029743, 5569230, 862349, 916122, 1038217, 987562, 1132771, 859075, 1127831, 837270, 845307, 1023958, 6034857, 995965, 1044078, 1107553, 5978656, 5569471, 908531, 986912]),
       list([5569230, 1029743, 995242, 981760, 1127831, 916122, 923746, 961554, 824005, 1005186, 854852, 962568, 903325, 866211, 6034857, 5978656, 859075, 1058997, 904360, 979707, 862349, 995965, 970030, 5569471, 987562, 951412, 1024306, 1053690, 874972, 951590, 878996, 1028816, 1004906, 908318, 1044078, 870515, 5569845, 1110843, 1136257, 1133018]),
       list([916122, 1058997, 1126899, 1005186, 961554, 981760, 824005, 5978656, 985999, 1127831, 862349, 951412, 1081177, 979707, 854852, 970030, 904360, 1119051, 1026118, 908318, 1053690, 12810393, 903325, 901062, 874972, 1136257, 1110843, 1070820, 897954, 944836, 995965, 6034857, 1039156, 970202, 859075, 962568, 1046262, 970119, 5569230, 1028816]),
       list([995242, 1029743, 986912, 1127831, 5978656, 981760, 878996, 866211, 1005186, 1077555, 1023720, 940947, 908531, 1105488, 1112238, 1117393, 854852, 904360, 1102949, 891141, 909894, 1133018, 951590, 1024306, 1002771, 5978648, 879528, 885290, 860975, 979707, 9526410, 1081189, 1043301, 1110843, 1076056, 5569230, 862349, 901062, 1027569, 1023958]),
       list([1133018, 1096036, 1033615, 981760, 1106523, 985119, 1065593, 1070015, 995242, 1044078, 844165, 909894, 1005186, 5592931, 6533765, 922907, 1114597, 1029743, 1062966, 1038217, 834833, 893018, 1023958, 8205218, 928049, 1043590, 1127758, 1026346, 1029624, 987562, 918368, 859075, 827683, 908531, 1134522, 883963, 1025611, 833025, 1103629, 910673]),
       list([995965, 897125, 965766, 844179, 896085, 981760, 857503, 1068719, 1014948, 1117514, 913210, 899624, 990797, 903325, 985999, 1081177, 951412, 12810393, 962568, 952317, 961554, 834117, 872137, 1074754, 8090513, 874972, 972931, 854852, 9245106, 954966, 5585510, 1057749, 979707, 5568729, 1022053, 1004906, 904360, 999858, 1029743, 1002771]),
       list([995242, 1029743, 981760, 923746, 859075, 844165, 1070015, 909894, 1068719, 5592931, 1004906, 1065593, 1033615, 6533765, 987562, 951590, 1043590, 904360, 985119, 1005186, 913785, 1133018, 885290, 1127758, 1096036, 1037863, 965766, 1092026, 1081177, 1044078, 1103629, 866211, 910673, 1062966, 1025611, 5585510, 871756, 892008, 1106523, 969866]),
       list([923746, 1106523, 1133018, 981760, 845208, 899624, 961554, 1004906, 962568, 866211, 874972, 1037863, 5978656, 863447, 847982, 1127831, 1024306, 878996, 1070702, 5978648, 1022254, 916122, 903325, 1000753, 1105623, 12946027, 1006184, 1038217, 902167, 1068719, 854852, 965766, 835098, 977545, 12810393, 822407, 882288, 993638, 1044078, 995965]),
       list([981760, 1106523, 1133018, 1068719, 1044078, 1065593, 1005186, 5592931, 951590, 1029743, 822407, 904360, 930917, 1004906, 859075, 1085604, 866211, 1033615, 1070015, 5568378, 909894, 1051211, 844179, 1101173, 1096036, 985119, 878996, 916122, 832678, 995242, 1127831, 6533765, 847982, 965766, 1062966, 1043590, 1134522, 1081177, 892008, 833025]),
       list([854852, 1106523, 899624, 1081177, 923746, 845208, 1004906, 1133018, 904360, 1037863, 981760, 844179, 5585510, 1044078, 962568, 910032, 1024306, 859075, 951590, 1127831, 871756, 1046545, 844165, 878996, 987562, 847982, 965766, 1053690, 1043590, 896613, 979707, 965267, 866211, 1092026, 1068719, 863447, 916122, 823704, 962229, 883932]),
       list([1029743, 995242, 981760, 1106523, 1133018, 1127831, 5569230, 951590, 1053690, 1044078, 986912, 1058997, 904360, 844165, 1070820, 1040807, 1126899, 854852, 1101010, 1016800, 1085604, 1092026, 1039156, 1005186, 910032, 866211, 5568378, 914190, 908531, 1132771, 883003, 878996, 1057260, 1077555, 933835, 827656, 862349, 833025, 923746, 844179]),
       list([908531, 909894, 1133018, 874972, 1127831, 859075, 995242, 5978656, 866211, 962568, 854852, 1106523, 1023958, 1006184, 1056509, 1044078, 961554, 833025, 862349, 1029743, 1070015, 983584, 878996, 847982, 1070820, 1024306, 995965, 965267, 981760, 993638, 913210, 863447, 5978648, 933835, 940947, 844179, 904360, 930118, 1105488, 860299]),
       list([1133018, 1106523, 904360, 981760, 833025, 908531, 1081177, 1029743, 1070820, 854852, 859075, 1053690, 1127831, 961554, 862349, 878996, 1004906, 962568, 923746, 995242, 909894, 1026118, 1044078, 903325, 1136257, 916122, 6034857, 899624, 1024306, 976199, 893501, 866211, 5568378, 5978656, 916381, 844179, 860975, 1056509, 983584, 901062]),
       list([986912, 971922, 981760, 933835, 883003, 1006184, 1138443, 885863, 961554, 995965, 847982, 1044078, 1026118, 866755, 999104, 995242, 862349, 845307, 1087102, 1101010, 1049735, 819978, 1081189, 931671, 1029743, 1043751, 904360, 1018740, 1040807, 1081177, 1070820, 914577, 12301405, 844179, 1110843, 1065593, 12810393, 5569327, 5978656, 9527290]),
       list([844179, 916122, 981760, 1044078, 965766, 999858, 1096036, 908531, 1065593, 995242, 904360, 12810393, 1004906, 987562, 962229, 1075368, 961554, 1029743, 930917, 923746, 833025, 1038217, 1006184, 979707, 859075, 844165, 893018, 847982, 865178, 999270, 995965, 976199, 1092026, 951590, 822407, 5568378, 1094955, 1068719, 1050851, 913785]),
       list([833025, 874972, 904360, 1081177, 940947, 824005, 995242, 1029743, 979707, 5568729, 923746, 962229, 981760, 1000753, 965766, 1127831, 9677202, 951412, 854852, 903325, 976199, 859075, 1058997, 962568, 908318, 834117, 951590, 1026118, 987724, 9527290, 878996, 909894, 1070702, 961554, 967395, 1004906, 1068719, 957951, 1002558, 993638]),
       list([981760, 1106523, 1133018, 5978656, 916122, 908531, 1044078, 1085604, 12810393, 904360, 962229, 1065593, 961554, 1081177, 8090521, 1004906, 6533765, 879755, 1092026, 995242, 844179, 1127831, 5568378, 986912, 1096036, 923746, 1029743, 870547, 859075, 5569327, 1038217, 1068719, 5569230, 909894, 930917, 5978648, 8090537, 866211, 1075368, 5592931]),
       list([1106523, 1133018, 981760, 951590, 1029743, 904360, 1053690, 923746, 1081177, 995242, 1127831, 1004906, 1044078, 844165, 5569230, 845208, 962229, 1092026, 8090521, 854852, 899624, 916381, 1037863, 5592931, 1026118, 5585510, 8090537, 910032, 878996, 5978656, 908531, 6533765, 1085604, 1065593, 1068719, 965766, 1096036, 844179, 866211, 1043590]),
       list([1133018, 1106523, 854852, 981760, 904360, 1081177, 951590, 995242, 1127831, 986912, 1029743, 979707, 883932, 1068719, 844179, 1024306, 878996, 962568, 1022254, 1053690, 1004906, 5978656, 965766, 1077555, 940947, 901062, 1132771, 845208, 1043301, 962229, 1026118, 9526410, 1037863, 832678, 1044078, 844165, 1070820, 945662, 890695, 1135834]),
       list([1029743, 995242, 1006184, 1133018, 986912, 1106523, 854852, 1081177, 995965, 6034857, 1051211, 1105488, 878996, 1112238, 880427, 916381, 1077555, 1005186, 1002771, 965267, 12946027, 865178, 1058779, 1074333, 9526410, 1056509, 1029112, 1027569, 1075368, 1091365, 863449, 885406, 847982, 1127831, 1044805, 945662, 1101567, 8069350, 854754, 9836460]),
       list([1062966, 1127624, 856772, 1096036, 985893, 5592931, 5569845, 8090537, 925626, 909894, 1134522, 1044078, 947798, 1065593, 1039156, 981760, 9527290, 928049, 8090521, 995242, 1043590, 1033615, 871756, 6533765, 1108131, 5569230, 1012587, 952317, 1114597, 8205218, 1076056, 988693, 962229, 1029624, 9526410, 873964, 951590, 1048462, 896369, 866211]),
       list([904360, 854852, 981760, 903325, 979707, 916122, 878996, 961554, 1127831, 962568, 1024306, 1023720, 872137, 866211, 844179, 1022254, 1051516, 995242, 1037863, 951412, 914190, 985999, 1102949, 5978656, 901062, 1029743, 1004906, 1119051, 1115576, 874149, 908318, 5978648, 6034857, 845208, 8090537, 1005274, 1105488, 870515, 1096036, 999858]),
       list([916122, 5978656, 981760, 824005, 985999, 961554, 1058997, 970030, 951412, 5978648, 1126899, 13842090, 12171656, 903325, 1127831, 909714, 1119051, 13842214, 6602729, 944836, 1005186, 1043787, 825541, 1082990, 6602697, 866211, 970202, 821083, 870515, 862010, 1080853, 970119, 828935, 897954, 908318, 1022097, 1046262, 1026118, 1028816, 1137688]),
       list([981760, 923746, 1133018, 1005186, 1106523, 1068719, 995242, 859075, 986912, 1044078, 987562, 1096036, 1029743, 951590, 844165, 5592931, 1043590, 904360, 1081177, 6533765, 1070015, 1039156, 1062966, 1004906, 1038217, 844179, 9526410, 871756, 909894, 845208, 1037863, 1065593, 962229, 833025, 1127831, 866211, 847982, 1033615, 878996, 879755]),
       list([981760, 995242, 1029743, 904360, 859075, 1044078, 5592931, 1133018, 1081177, 1096036, 1004906, 1106523, 833025, 844179, 1043590, 1068719, 854852, 987562, 845208, 844165, 1062966, 923746, 979707, 893018, 6533765, 916122, 918368, 1026118, 987724, 951590, 1037863, 1136257, 918335, 1065593, 1069621, 1002558, 9527290, 1038217, 871756, 899624]),
       list([981760, 951590, 866211, 878996, 1122358, 1029743, 1127831, 995242, 5978656, 879755, 1106523, 909894, 1095040, 986912, 1039156, 908531, 1004906, 904360, 1024731, 923746, 1133018, 844165, 821083, 843744, 1037863, 1025628, 1085604, 1138189, 962229, 1076056, 983584, 856827, 1125199, 827570, 1048462, 885290, 961554, 844179, 908504, 8090537]),
       list([1081177, 904360, 854852, 6034857, 1029743, 995242, 981760, 1136257, 962568, 859075, 961554, 1044078, 1026118, 1137688, 824005, 844179, 995965, 903325, 1004906, 833025, 845208, 916122, 1037863, 979707, 970202, 1110142, 987724, 870515, 918368, 976199, 970119, 1127831, 862349, 1133018, 1034686, 874972, 1028816, 908531, 824073, 1068719]),
       list([903325, 1127831, 951412, 1023720, 854852, 901062, 879528, 7024990, 1137688, 1022254, 979707, 1042697, 1051516, 1102949, 866211, 878996, 1127179, 1028816, 1058997, 933637, 5578547, 999104, 870515, 891141, 901666, 981760, 5978648, 962568, 1026118, 1098248, 1057102, 904360, 922127, 872137, 961554, 869177, 909714, 6552253, 925425, 852856]),
       list([8090521, 995242, 1029743, 8090537, 885290, 940947, 8090536, 12301405, 1130763, 1062002, 971922, 1092026, 908531, 5569230, 890695, 5568378, 1137346, 856772, 981760, 962229, 1040807, 1041796, 930917, 13506200, 5568729, 1127831, 979707, 957736, 1082212, 883932, 993466, 999104, 1058997, 1126899, 831063, 844179, 5978656, 5569327, 965766, 896085]),
       list([1058997, 961554, 981760, 916122, 1126899, 6034857, 979707, 1127831, 903325, 5978656, 904360, 854852, 862349, 970119, 951412, 962568, 865178, 824005, 1081177, 1119051, 870515, 1022254, 878996, 916993, 5978648, 976199, 1070820, 866211, 1026118, 1137688, 825541, 1116821, 1000237, 5569471, 970030, 821083, 1027569, 1005186, 908531, 995965]),
       list([1029743, 1106523, 1133018, 995242, 981760, 5592931, 1053690, 1096036, 844165, 1065593, 1044078, 1068719, 951590, 1033615, 859075, 1081177, 1062966, 1092026, 833025, 904360, 1070015, 5569230, 893018, 1043590, 6533765, 923746, 985119, 1038663, 1038217, 1004906, 987562, 9527290, 8090537, 999779, 916381, 844179, 1051323, 5568378, 883963, 8090521]),
       list([901062, 9526410, 879528, 1102949, 854852, 10121965, 965766, 1116821, 981760, 961554, 951590, 979707, 970030, 903325, 1136257, 865178, 1106523, 1058997, 1055425, 1133018, 913785, 824005, 870515, 872137, 866211, 916122, 904360, 995242, 1127831, 1126899, 1043301, 868548, 933835, 1046262, 5569230, 885023, 1077490, 913894, 12263788, 878996]),
       list([5592931, 981760, 1106523, 1096036, 1134522, 1133018, 1033615, 856772, 1065593, 1044078, 893018, 923746, 1062966, 5978656, 883963, 1029743, 8205218, 1068719, 1026346, 985119, 952317, 1043590, 1127624, 1042438, 833025, 928049, 844179, 1038217, 5978648, 1118533, 8119303, 925626, 1004906, 5569327, 858302, 1095700, 1003188, 1122358, 904360, 9420312]),
       list([995242, 1005186, 1029743, 1065593, 1077555, 859075, 981760, 909894, 951590, 908531, 847982, 860975, 1110843, 5978656, 1056509, 1096036, 1039156, 986912, 1038217, 913785, 904360, 833025, 1006184, 5569230, 1091365, 1023958, 1127831, 916122, 9526410, 913210, 1004906, 1044078, 844179, 961554, 862349, 933835, 944139, 1092026, 1058779, 5568378]),
       list([995242, 908531, 1029743, 981760, 5978656, 1127831, 1005186, 986912, 862349, 961554, 909894, 866211, 1085604, 962229, 1107553, 904360, 1058997, 859075, 923746, 878996, 1070820, 1126899, 1110843, 847982, 5569230, 1110572, 860975, 5978648, 863802, 1091365, 1053690, 879755, 1073150, 916122, 1006184, 983584, 861445, 1065593, 951590, 1024306]),
       list([859075, 904360, 1029743, 930917, 893018, 961554, 1096036, 866211, 990797, 1045220, 5569845, 1038217, 1004906, 981760, 1081177, 12810393, 1127624, 5569230, 995242, 822407, 897125, 925626, 1127831, 987562, 916122, 892008, 1136257, 1002558, 844179, 9526411, 859010, 1108168, 839419, 1106301, 5978648, 1068719, 1044078, 1024306, 1050851, 5568378]),
       list([1133018, 1106523, 981760, 909894, 5978656, 1023958, 860975, 847982, 908531, 878996, 1127831, 986912, 5978648, 1023720, 1096036, 993638, 923746, 904360, 866211, 1039156, 1038217, 1065593, 890610, 12810393, 845208, 1044078, 1006184, 961554, 1070015, 1058779, 877447, 933637, 1062966, 939636, 905539, 1004906, 1026118, 1024306, 854852, 944534]),
       list([995242, 1029743, 981760, 904360, 908531, 854852, 1127831, 1081177, 859075, 1044078, 961554, 923746, 1024306, 844179, 962568, 878996, 916122, 833025, 979707, 986912, 903325, 862349, 5978656, 1053690, 893501, 866211, 1096036, 951590, 909894, 976199, 1105488, 6034857, 1133018, 1136257, 5569230, 901062, 1005186, 1058997, 844165, 1070820]),
       list([995242, 1029743, 981760, 1053690, 5569230, 1127831, 1070820, 5569471, 951590, 862349, 986912, 1058997, 904360, 1005186, 1126899, 844165, 893501, 5569374, 1106523, 1065593, 940947, 878996, 1044078, 1039156, 854852, 868764, 1081177, 962229, 844179, 923746, 908531, 883932, 1082212, 916122, 1133018, 1027569, 1024306, 910032, 1077555, 1091365]),
       list([961554, 1071342, 845208, 923746, 1024306, 8090521, 5978656, 1135460, 1053690, 878996, 890610, 990688, 5569845, 1109374, 6533765, 5978648, 1076056, 897953, 1018670, 879755, 1070820, 1127831, 8119157, 1085604, 846334, 937626, 1125943, 1023720, 931671, 981760, 909714, 822407, 862349, 882941, 922651, 1026209, 930917, 1007082, 878290, 1037863]),
       list([1106523, 1133018, 1029743, 1053690, 995242, 951590, 859075, 5569230, 981760, 1044078, 908531, 833025, 1092026, 9526410, 1056509, 904360, 962229, 899624, 1085604, 1081177, 923746, 1132771, 1077555, 1101010, 893501, 1068719, 933835, 1040807, 844165, 987562, 5568378, 822407, 854852, 916381, 1136257, 1062966, 1127831, 962568, 5978656, 1043751]),
       list([1029743, 995242, 1092026, 1053690, 981760, 859075, 5568378, 5569230, 951590, 1044078, 8090521, 1065593, 916122, 1006184, 962229, 1127831, 904360, 961554, 844179, 844165, 847982, 834117, 1085604, 1081177, 9527290, 866211, 5569327, 987562, 1004906, 9526410, 916381, 933835, 1136257, 833025, 1101173, 913210, 893501, 908531, 1040807, 8090537]),
       list([995242, 1029743, 1026118, 981760, 986912, 1037863, 1044078, 1133018, 904360, 1053690, 993638, 1106523, 845208, 923746, 1004906, 1127831, 951590, 878996, 854852, 1028816, 866211, 934639, 1081177, 969866, 1022254, 863447, 916122, 916381, 965267, 909894, 1023720, 844165, 860975, 1068719, 6533765, 962568, 1051516, 871611, 896613, 1062966]),
       list([844179, 874972, 854852, 1044078, 1133018, 899624, 833025, 916122, 1070702, 981760, 1000753, 5569230, 1106523, 883932, 1004906, 951590, 1049788, 995242, 1068719, 880150, 12810393, 845208, 5978648, 828106, 979707, 1046545, 1081177, 835098, 1077490, 863447, 904360, 1029743, 825541, 999858, 1056509, 848029, 859075, 1132771, 946995, 1022254]),
       list([5569471, 1042438, 1101010, 930917, 1068719, 1038217, 1018740, 1051211, 908318, 819978, 1058997, 977545, 933835, 883932, 892008, 1043751, 1106301, 823704, 995242, 1105623, 1027569, 1045220, 1081177, 1124507, 866211, 5585510, 921504, 885863, 995965, 1040807, 970202, 940947, 847344, 859075, 819255, 1039156, 882288, 1138443, 859010, 5569230]),
       list([1005186, 859075, 981760, 5978656, 951590, 995242, 9526410, 1044078, 847982, 844179, 5569230, 1038217, 1085604, 1127831, 845208, 1068719, 1029743, 1037894, 5569845, 904360, 8090537, 908531, 1077555, 1065593, 879755, 1096036, 1004906, 1110572, 8090521, 944139, 910032, 1133018, 866211, 5592931, 5978648, 987562, 1006184, 961554, 1081177, 12810393]),
       list([914190, 9527494, 832678, 856772, 1127831, 1134522, 971922, 1042438, 9526411, 1058997, 957736, 933835, 995965, 8090532, 845307, 1138443, 1087102, 1126899, 9527160, 5568378, 5569327, 908318, 1040807, 9526410, 981760, 874972, 951590, 845193, 972665, 903325, 898068, 5978656, 858302, 979707, 901776, 890695, 1006184, 883003, 1132771, 844179]),
       list([933835, 9526410, 914190, 1081177, 844179, 995965, 845208, 6034857, 859075, 1006184, 1087102, 1138443, 995242, 1005186, 951590, 908318, 854852, 948670, 1110843, 1040807, 5978656, 981521, 990797, 1063207, 5978648, 901062, 962229, 12810393, 909268, 854405, 883003, 961554, 845307, 1135834, 871061, 5585510, 1068719, 9245106, 1042438, 970119]),
       list([1029743, 995242, 5569230, 8090521, 951590, 1133018, 1106523, 8090537, 1053690, 981760, 1065593, 1092026, 916122, 1004906, 1044078, 908531, 5569845, 962229, 904360, 844165, 844179, 1075368, 5568378, 1127831, 8090509, 12810393, 833025, 1081177, 9527290, 5978656, 1085604, 965766, 916381, 910032, 913785, 866211, 944139, 834117, 909894, 930917]),

In [223]:
np.concatenate(users_lvl_2_part.candidates.values)

array([ 923746, 1029743, 1044078, ..., 1118787, 1022066,  897752],
      dtype=int64)

In [225]:
users_lvl_2_part.user_id.values.repeat(len(users_lvl_2_part.candidates[0]))

array([2070, 2070, 2070, ..., 1388, 1388, 1388], dtype=int64)

In [227]:
# Создадим "технический" датафрейм df с разбиением на пары "юзер-айтем"
df=pd.DataFrame({'user_id':users_lvl_2_part.user_id.values.repeat(len(users_lvl_2_part.candidates[0])),
                 'item_id':np.concatenate(users_lvl_2_part.candidates.values)})
df

       user_id  item_id
0         2070   923746
1         2070  1029743
2         2070  1044078
3         2070  1096036
4         2070   896369
...        ...      ...
19995     1388  1053690
19996     1388  1016800
19997     1388  1118787
19998     1388  1022066
19999     1388   897752

[20000 rows x 2 columns]

In [232]:
# Создадим датафрейм targets_lvl_2 из исходного data_train_lvl_2
targets_lvl_2 = data_train_lvl_2[['user_id', 'item_id']].copy()
#Введем столбец покупок
targets_lvl_2['target'] = 1  # тут только покупки

In [238]:
targets_lvl_2.shape

(169711, 3)

In [233]:
# Выберем также тех же 500 пользователей, чтобы совпадали с вынужденно укороченным датафреймом users_lvl_2_part
targets_lvl_2_part = targets_lvl_2.loc[targets_lvl_2['user_id'].isin(df['user_id'].tolist ())]
targets_lvl_2_part.user_id.nunique()

500

In [234]:
targets_lvl_2_part

         user_id  item_id  target
2104867     2070   999999       1
2107468     2021   999999       1
2107469     2021   856060       1
2107470     2021   869344       1
2107471     2021   896862       1
...          ...      ...     ...
2279981     1769   926549       1
2279982     1769   943137       1
2279983     1769  1039156       1
2279984       23   999999       1
2279988      975   999999       1

[60232 rows x 3 columns]

In [235]:
# Объединяем датафреймы
targets_lvl_2_part = df.merge(targets_lvl_2_part, on=['user_id', 'item_id'], how='left')
targets_lvl_2_part

       user_id  item_id  target
0         2070   923746     NaN
1         2070  1029743     NaN
2         2070  1044078     NaN
3         2070  1096036     NaN
4         2070   896369     NaN
...        ...      ...     ...
22868     1388  1016800     NaN
22869     1388  1118787     NaN
22870     1388  1022066     1.0
22871     1388  1022066     1.0
22872     1388   897752     NaN

[22873 rows x 3 columns]

In [239]:
# Заполняем пропуски в 'target'

targets_lvl_2_part['target'].fillna(0, inplace= True)

In [240]:
targets_lvl_2_part.shape

(22873, 3)

In [310]:
# Объединяем датафреймы с характеристиками "юзеров" и "айтемов"
targets_lvl_2_part = targets_lvl_2_part.merge(item_features, on='item_id', how='left') #
targets_lvl_2_part = targets_lvl_2_part.merge(user_features, on='user_id', how='left') #

targets_lvl_2_part.head()

,user_id,item_id,target,manufacturer_x,department_x,brand_x,commodity_desc_x,sub_commodity_desc_x,curr_size_of_product_x,age_desc_x,...,age_desc,marital_status_code,income_desc,homeowner_desc,hh_comp_desc,household_size_desc,kid_category_desc,bill_avg,week_last_bill,items_per_week
0,2070,923746,0.0,69,GROCERY,Private,EGGS,EGGS - LARGE,18 CT,45-54,...,45-54,U,50-74K,Unknown,Unknown,1,None/Unknown,2.891039,95.0,29.814815
1,2070,1029743,0.0,69,GROCERY,Private,FLUID MILK PRODUCTS,FLUID MILK WHITE ONLY,1 GA,45-54,...,45-54,U,50-74K,Unknown,Unknown,1,None/Unknown,2.891039,95.0,29.814815
2,2070,1044078,0.0,2845,MEAT,National,BEEF,LEAN,,45-54,...,45-54,U,50-74K,Unknown,Unknown,1,None/Unknown,2.891039,95.0,29.814815
3,2070,1096036,0.0,69,GROCERY,Private,CHEESE,IWS SINGLE CHEESE,12 OZ,45-54,...,45-54,U,50-74K,Unknown,Unknown,1,None/Unknown,2.891039,95.0,29.814815
4,2070,896369,0.0,69,GROCERY,Private,PNT BTR/JELLY/JAMS,PEANUT BUTTER,18 OZ,45-54,...,45-54,U,50-74K,Unknown,Unknown,1,None/Unknown,2.891039,95.0,29.814815

In [243]:
targets_lvl_2_part.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22873 entries, 0 to 22872
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               22873 non-null  int64
 1   item_id               22873 non-null  int64
 2   target                22873 non-null  float64
 3   manufacturer          22873 non-null  int64
 4   department            22873 non-null  object
 5   brand                 22873 non-null  object
 6   commodity_desc        22873 non-null  object
 7   sub_commodity_desc    22873 non-null  object
 8   curr_size_of_product  22873 non-null  object
 9   age_desc              12428 non-null  object
 10  marital_status_code   12428 non-null  object
 11  income_desc           12428 non-null  object
 12  homeowner_desc        12428 non-null  object
 13  hh_comp_desc          12428 non-null  object
 14  household_size_desc   12428 non-null  object
 15  kid_category_desc     12428 non-null  object
 16  bill_avg              12428 non-null  float64
 17  week_last_bill        12428 non-null  float64
 18  items_per_week        12428 non-null  float64
dtypes: float64(4), int64(3), object(12)
memory usage: 3.5+ MB

In [244]:
# Видно наличие пустых ячеек. Заполняем их нулями.
targets_lvl_2_part.fillna(0, inplace=True)

In [245]:
# Готовим X_train и у_train
X_train = targets_lvl_2_part.drop('target', axis=1)
y_train = targets_lvl_2_part[['target']]

In [246]:
cat_feats = X_train.columns[2:].tolist()
X_train[cat_feats] = X_train[cat_feats].astype('category')

cat_feats

['manufacturer',
 'department',
 'brand',
 'commodity_desc',
 'sub_commodity_desc',
 'curr_size_of_product',
 'age_desc',
 'marital_status_code',
 'income_desc',
 'homeowner_desc',
 'hh_comp_desc',
 'household_size_desc',
 'kid_category_desc',
 'bill_avg',
 'week_last_bill',
 'items_per_week']

In [248]:
lgb = LGBMClassifier(objective='binary', 
                     n_estimators=1500,
                     learning_rate=0.008,
                     max_depth=7, 
                     verbose=1,
                     categorical_column=cat_feats)

hist = lgb.fit(X_train, y_train, 
               eval_set=[(X_train, y_train)],
               eval_metric=['logloss']
               )

train_preds = lgb.predict_proba(X_train)

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Number of positive: 6617, number of negative: 16256
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002911 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1803
[LightGBM] [Info] Number of data points in the train set: 22873, number of used features: 18
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.289293 -> initscore=-0.898820
[LightGBM] [Info] Start training from score -0.898820
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).

In [259]:
train_preds

array([[0.63368842, 0.36631158],
       [0.41158958, 0.58841042],
       [0.66827877, 0.33172123],
       ...,
       [0.17141922, 0.82858078],
       [0.17141922, 0.82858078],
       [0.87687579, 0.12312421]])

In [260]:
hist.evals_result_['training']['binary_logloss'][-10:]

[0.35633661910648684,
 0.35627424783613804,
 0.35617925316004145,
 0.35609588325084385,
 0.3560279722403082,
 0.35596658632930744,
 0.35590413175142205,
 0.35584129434514417,
 0.3557865761166094,
 0.35571688791467027]

In [251]:
# Создадим датафрейм с вероятностями
classifer_prediction = X_train[['user_id', 'item_id']]
classifer_prediction["pred"] = train_preds[:, 1]
classifer_prediction.tail()

       user_id  item_id      pred
22868     1388  1016800  0.096407
22869     1388  1118787  0.121448
22870     1388  1022066  0.828581
22871     1388  1022066  0.828581
22872     1388   897752  0.123124

In [262]:
# Оставим итемы с вероятностями больше 0,5
res_val = classifer_prediction.loc[classifer_prediction["pred"]>0.5, ["user_id", "item_id"]]
res_val.tail()

       user_id  item_id
22831     1388  1029743
22857     1388  1081189
22858     1388  1081189
22870     1388  1022066
22871     1388  1022066

In [263]:
res_val.shape

(4297, 2)

In [264]:
res_val.user_id.nunique()

282

In [265]:
# Создаем датафрейм рекомендаций на основе датафрейма res_val
pred_lvl_2_part = res_val.groupby('user_id')['item_id'].unique().reset_index()
pred_lvl_2_part.columns=['user_id', 'pred']
pred_lvl_2_part.head()

   user_id                                               pred
0       13  [859075, 1126899, 1029743, 5978656, 1058997, 9...
1       19  [965766, 865456, 899624, 1101173, 1046545, 844...
2       20  [1058997, 1126899, 1075368, 1123106, 894360, 9...
3       23        [1029743, 1075368, 844165, 962229, 1106523]
4       27  [1077555, 1052920, 1102416, 9419470, 1029252, ...

In [257]:
result_lvl_2_part = result_lvl_2_part.merge(pred_lvl_2_part, on='user_id', how='left')
result_lvl_2_part.head()

,user_id,actual,pred
0,13,"[999999, 1104146, 862070, 886317, 950439, 9815...","[859075, 1126899, 1029743, 5978656, 1058997, 9..."
1,14,"[840601, 867293, 933067, 951590, 952408, 96569...",NaN
2,18,"[831628, 999999, 914697, 995242, 1118878, 1128...",NaN
3,20,"[819112, 944419, 945611, 999999, 1058997, 5592...","[1058997, 1126899, 1075368, 1123106, 894360, 9..."
4,22,"[999999, 849470, 858743, 916758, 935968, 10105...",NaN

In [269]:
# Определяем количество НЕ ПУСТЫХ ячеек
user_pred_nan = result_lvl_2_part.loc[result_lvl_2_part["pred"] != result_lvl_2_part["pred"], 'user_id'].values
len(user_pred_nan)

375

In [274]:
set_tr_1 = set(data_train_lvl_1.user_id.unique())
len(set_tr_1)

2498

In [275]:
# Находим пересечение пользователей из валидационного и обучаемого датасетов
user_list = set(user_pred_nan).intersection(set_tr_1)
len(user_list)

375

In [277]:
result_lvl_2_part.loc[result_lvl_2_part["user_id"].isin(user_list), "user_id"]

1        14
2        18
4        22
6        28
7        35
       ...
493    2461
494    2462
495    2465
497    2481
499    2500
Name: user_id, Length: 375, dtype: int64

In [276]:
result_lvl_2_part.loc[result_lvl_2_part["user_id"].isin(user_list), "pred"] =\
result_lvl_2_part.loc[result_lvl_2_part["user_id"].isin(user_list), "user_id"].apply(lambda x: recommender.get_als_recommendations(x, rec_num=k_n))
result_lvl_2_part.head()

,user_id,actual,pred
0,13,"[999999, 1104146, 862070, 886317, 950439, 9815...","[859075, 1126899, 1029743, 5978656, 1058997, 9..."
1,14,"[840601, 867293, 933067, 951590, 952408, 96569...","[995242, 1029743, 981760, 951590, 6533765]"
2,18,"[831628, 999999, 914697, 995242, 1118878, 1128...","[903325, 916122, 951412, 995965, 961554]"
3,20,"[819112, 944419, 945611, 999999, 1058997, 5592...","[1058997, 1126899, 1075368, 1123106, 894360, 9..."
4,22,"[999999, 849470, 858743, 916758, 935968, 10105...","[1070820, 862349, 5978656, 5978648, 854852]"

In [285]:
result_lvl_2_part.loc[result_lvl_2["user_id"] == 14]

,user_id,actual,pred
7,35,"[1089888, 5591609, 6423775]","[1058997, 1126899, 908531, 1029743, 995242]"

In [286]:
# Выделим пять наиболее популярных товаров (исходя из количества продаж) из всего исходного датасета 
popularity = recommender.prep_data.groupby('item_id')['quantity'].sum().reset_index()
popularity.rename(columns={'quantity': 'n_sold'}, inplace=True)
top_5 = popularity.sort_values('n_sold', ascending=False).head(6).item_id.tolist()[1:6]
top_5

[995242, 1029743, 1133018, 981760, 1106523]

In [291]:
# Внедряем эти товары
result_lvl_2_part.loc[result_lvl_2_part["user_id"] == 14, "pred"] =\
        result_lvl_2_part.loc[result_lvl_2["user_id"] == 14, "user_id"].apply(lambda x: top_5)

In [299]:
# Проверяем работоспособность
result_lvl_2_part.loc[result_lvl_2["user_id"] == 14]

,user_id,actual,pred
7,35,"[1089888, 5591609, 6423775]","[995242, 1029743, 1133018, 981760, 1106523]"

In [300]:
len(result_lvl_2_part.loc[result_lvl_2["user_id"] == 14, "pred"].values[0])

5

In [301]:
# Формируем рабочий список
res = []
res.extend(result_lvl_2_part.loc[result_lvl_2["user_id"] == 14, "pred"].values[0])
res

[995242, 1029743, 1133018, 981760, 1106523]

In [306]:
# Подпрограмма для заполнения недостающих рекомендуемых значений до пяти
def fill_if_not_5(recommender, x):
    res = []
    res.extend(result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "pred"].values[0])
    pred_num = len(result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "pred"].values[0])
    if pred_num < 5:
        res.extend(recommender.get_als_recommendations(x, rec_num=5-pred_num))
    return res

In [307]:
# Если рекомендуемых товаров получилось меньше пяти - "добиваем" их до пяти
result_lvl_2_part["pred"] = result_lvl_2_part["user_id"].apply(lambda x: fill_if_not_5(recommender, x))

In [312]:
result_lvl_2_part.head()

,user_id,actual,pred
0,13,"[999999, 1104146, 862070, 886317, 950439, 9815...","[859075, 1126899, 1029743, 5978656, 1058997, 9..."
1,14,"[840601, 867293, 933067, 951590, 952408, 96569...","[995242, 1029743, 981760, 951590, 6533765]"
2,18,"[831628, 999999, 914697, 995242, 1118878, 1128...","[903325, 916122, 951412, 995965, 961554]"
3,20,"[819112, 944419, 945611, 999999, 1058997, 5592...","[1058997, 1126899, 1075368, 1123106, 894360, 9..."
4,22,"[999999, 849470, 858743, 916758, 935968, 10105...","[1070820, 862349, 5978656, 5978648, 854852]"

In [313]:
result_lvl_2_part["rec"] = result_lvl_2_part['user_id'].apply(\
        lambda x: precision_at_k(result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "pred"].values[0], 
                                 list(result_lvl_2_part.loc[result_lvl_2_part["user_id"] == x, "actual"].values[0]), 
                                 k=5))

result_lvl_2_part['rec'].mean()

0.2800000000000004

## Целевая метрика precision@5 получилась равной 0.28

### Готовим выходной файл с рекомендациями recommendations.csv

In [317]:
recom = result_lvl_2_part.drop(['actual', 'rec'], axis=1)
recom

     user_id                                               pred
0         13  [859075, 1126899, 1029743, 5978656, 1058997, 9...
1         14         [995242, 1029743, 981760, 951590, 6533765]
2         18           [903325, 916122, 951412, 995965, 961554]
3         20  [1058997, 1126899, 1075368, 1123106, 894360, 9...
4         22        [1070820, 862349, 5978656, 5978648, 854852]
..       ...                                                ...
495     2465           [981760, 986912, 923746, 904360, 993638]
496     2475  [1070820, 883003, 5569471, 971922, 1070845, 10...
497     2481         [1029743, 833025, 995242, 904360, 1133018]
498     2498       [1070820, 1053690, 5569230, 862349, 1070820]
499     2500       [5978656, 1106523, 1133018, 5978648, 859075]

[500 rows x 2 columns]

In [318]:
recom.to_csv("./prep12/recommendations.csv", index=False)